### ISSUE TITLE
the unnormal return code of post request can not be get

### ISSUE THREAD

**Issue by ayumukid** [yhirose/cpp-httplib#586] opened 2020-07-29 09:04 UTC
well ,there is a very good to use. there was a problem I found, where the return status code is not 200, for example 400
the post method can not get the return code.

the code is like this:
		auto res = m_cImage->Post(strUrl.c_str(), headers, items);

		if (res != nullptr)
		{
			bRet = res->status;
			strResponse = res->body;
		}
		else
		{
			PLGZF_INFO("上传图片 报文返回为空");
                }
but in fact, the response packet is:
 
HTTP/1.1 400 Bad Request
Content-Length: 67
Date: Wed,29 Jul 20 06:13:42 GMT
Connection: close

{
   "ErrorCode" : "-58005",
   "Message" : "pic token illegal"
}

**Comment by PixlRainbow** [comment] 2020-07-29 09:25
I could not reproduce the issue when sending request to httpbin.org using its status 400 test.  
If you run cpp-httplib's included test suite, do all tests pass for you?

**Comment by ayumukid** [comment] 2020-07-29 12:20
i  used httplib in   keep-alive  mode and in threads.  ,i  used vs2015,and i didn't run the tests. 

> I could not reproduce the issue when sending request to httpbin.org using its status 400 test.
> If you run cpp-httplib's included test suite, do all tests pass for you or do some fail?

**Comment by yhirose** [comment] 2020-07-29 12:28
@ayumukid, thanks for the feedback. I don't think it's caused by cpp-httplib. Could you run the test suite on your machine please? The test already includes the following test:

https://github.com/yhirose/cpp-httplib/blob/342c3ab2930e6639ead484bca88a9dd7a8724239/test/test.cc#L1367-L1382

Thanks!

**Comment by ayumukid** [comment] 2020-07-29 12:30
> @ayumukid, thanks for the feedback. I don't think it's caused by cpp-httplib. Could you run the test suite on your machine please? The test already includes the following test:
> 
> https://github.com/yhirose/cpp-httplib/blob/342c3ab2930e6639ead484bca88a9dd7a8724239/test/test.cc#L1367-L1382
> 
> Thanks!

ok,i will have a try.

**Comment by yhirose** [comment] 2020-07-30 22:29
@ayumukid, since it looks different from a problem in cpp-httplib, I'll close it for now. If you find a clear evidence, please let me know. Thanks!

**Closed by yhirose** 2020-07-30 22:29 UTC

**Comment by ayumukid** [comment] 2020-07-31 06:25
i run the test cases,it pass

**Comment by ayumukid** [comment] 2020-07-31 06:31
I used in keep-alive mode, and I set the timeout ,i guess the problem is bug#591, i will use the new version to test
