### ISSUE TITLE
Segfault when the server does not respond

### ISSUE THREAD

**Issue by TR-SLimey** [yhirose/cpp-httplib#428] opened 2020-04-14 21:16 UTC
I have set up a Python TCP server to print everything sent to it for debugging. The server does not send a reply but closes the socket after it receives any data. This results in a segfault and consequently, the program crashing.

The Python TCP server works as follows:
```
import socket, sys

def listen():
    connection = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    connection.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    connection.bind(('0.0.0.0', int(sys.argv[1])))
    connection.listen(10)
    while True:
        current_connection, address = connection.accept()
        print(address[0])
        data = current_connection.recv(4096)
        if data: print(data.decode())
        current_connection.send(b"")
        current_connection.close()

if __name__ == "__main__":
    try:
        listen()
    except KeyboardInterrupt:
        pass
```
Something should probably be added to make the library more robust when connecting to a non-compliant server.

**Comment by yhirose** [comment] 2020-04-15 03:13
@TR-SLimey, thanks for the report. But I couldn't reproduce it. Actually, the following sample cpp-httplib client returned successfully, but the python server crashed instead at `print(address[0])` due to the data conversion error...

**Server**
```bash
# copy your server code to 'server.py'
> python server.py 8080
127.0.0.1
Traceback (most recent call last):
  File "server.py", line 18, in <module>
    listen()
  File "server.py", line 12, in listen
    if data: print(data.decode())
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8d in position 12: ordinal not in range(128)
```

**Client**
```bash
> cd example
> make client
>./client
> echo $?
> 0
```

Could you show me the smallest possible client code that causes the problem that you mentioned, also the correct server code without the data conversion problem?
For now, I close this issue until I can reproduce it on my machine. Thanks for your help!

**Closed by yhirose** 2020-04-15 03:13 UTC

**Comment by TR-SLimey** [comment] 2020-04-15 12:52
Weirdly, now I myself can't reproduce the error. I'm sure it was to do with httplib as commenting it out removed the segfault. However, with the edits I have done to my code since making the report, all seems well. Furthermore, a minimal client also works flawlessly. Maybe the error was to do with me statically linking some libraries though I can't remember which ones since I'm no longer doing that.

Anyway, I guess the problem is solved.

As for the Python server, are you sure it crashed at the first `print`? If that's the case I would assume you used Python2 instead of Python3. It does normally crash for HTTPS connections on line 12 since it can't decode the message sent. To avoid it crashing you can just remove the `.decode()` on line 12.
