### ISSUE TITLE
SSLServer and multipart data

### ISSUE THREAD

**Issue by KevinSmild** [yhirose/cpp-httplib#321] opened 2020-01-08 07:03 UTC
Hello, yhirose. 
First of all thanks for the library. Is pretty complete and easy to use.

There's a small problem when trying to receive multipart/form-data using a SSLServer. I tried to upload an image file (of size 22.7 KB) and a text/plain data together in one request, but the server only seems to recognize the first item while ignoring the last one.

Thanks, 
Kevin.

**Comment by yhirose** [comment] 2020-01-08 17:58
@KevinSmild, thank you for the bug report. Do you have small example code that I can use to reproduce the problem on my machine?

**Comment by yhirose** [comment] 2020-01-10 23:41
@KevinSmild, I simulated your situation with 'example/upload.cc', but it worked fine.
https://github.com/yhirose/cpp-httplib/blob/master/example/upload.cc

So I'll close it for now since I can't reproduce it. Please let me know if you have more detail. Thank you!

**Comment by KevinSmild** [comment] 2020-01-16 04:44
@yhirose  I am so sorry. I got busy and completely forgot. 
The error only seems to appear when using SSLSever.

This is the code I'm using to reproduce the error
![code](https://user-images.githubusercontent.com/17018207/72492344-d2502780-3857-11ea-80fe-c96bbe08dee2.png)

This is the result using Postman sending only one field
![one_param](https://user-images.githubusercontent.com/17018207/72493961-6f618f00-385d-11ea-8360-895e852013f7.png)

And this is the result with two fields:
![two_params](https://user-images.githubusercontent.com/17018207/72493976-77b9ca00-385d-11ea-8fcd-911e814ad98b.png)

Again, this error only seems to happen while using a SSLServer.

Really sorry, and thanks again.
Kevin

**Comment by yhirose** [comment] 2020-01-16 13:10
@KevinSmild, thanks for the more information. I'll take a look at it when I have time. Thanks!

**Comment by yhirose** [comment] 2020-01-17 02:27
@KevinSmild, thanks for the detail. I just wonder if this problem has been fixed with the latest master, because it's very similar to #332. Could you try your test case with the latest master code? Thank you!

**Closed** 2020-01-25 05:01 UTC
