### ISSUE TITLE
Getting xstring error whens ending POST request.

### ISSUE THREAD

**Issue by syrex1013** [yhirose/cpp-httplib#752] opened 2020-11-12 14:43 UTC
Hi,
I keep getting xstring error on all of my projects using httplib.
Here is sample code:
`httplib::Client cli(url.c_str());            
    auto res = cli.Post(path.c_str(), data.c_str(), "application/x-www-form-urlencoded");                       
    string body = res->body;                  
    return body;                      `
And the error:
![obraz](https://user-images.githubusercontent.com/31669127/98954068-b2cc6e80-24fd-11eb-926a-bca5ea7b4eef.png)

Any ideas what might have caused it?

**Comment by yhirose** [comment] 2020-11-12 15:51
@syrex1013, could you give me a simple code example?

**Comment by syrex1013** [comment] 2020-11-12 15:55
It is in my question.
It is just like in your example on github.
`httplib::Client cli(url.c_str());                  
auto res = cli.Post(path.c_str(), data.c_str(), "application/x-www-form-urlencoded");                       
string body = res->body;               
return body;                      `

url is set to "somedomain.com"
path to "/file.php"
data to "a=b&c=d"

**Comment by syrex1013** [comment] 2020-11-12 16:04
I can also add that it throws this error randomly. Sometimes it works and sometimes it doesn't.                        
Data is not changing and server returns the same response always, so idk what causes this.

**Comment by yhirose** [comment] 2020-11-12 16:09
@syrex1013, you code is pretty basic, and looks good. So the problem is caused not by httplib.h, but something outside of this library.

The following test does exactly same as you are doing and works fine on unit tests on all the platform (Windows, Mac, Linux) on GItHub Action workflow.

https://github.com/yhirose/cpp-httplib/blob/9c7d841b37b69cde4ffb7c6d5c1aae6d5d6e1d97/test/test.cc#L1477-L1492

So I can't give you any further meaningful information unless I can reproduce it on my machine.

**Comment by syrex1013** [comment] 2020-11-12 16:15
Well, thanks for help anyways! I try to get more info, and come back here,

**Comment by yhirose** [comment] 2020-11-29 22:24
@syrex1013, I"ll close it for now. Please let me know if you find further information on this and it's a reproducible, then I'll reopen this issue. Thanks!

**Closed by yhirose** 2020-11-29 22:24 UTC
Labels: need more information to verify
