### ISSUE TITLE
client post failed

### ISSUE THREAD

**Issue by runningJ** [yhirose/cpp-httplib#362] opened 2020-02-24 01:58 UTC
`int port = json_port->valueint;
    string image_path = "/opt/datasets/readwinelibrary/992E4631-F6A9-4208-841B-14A50314746C/b563ae35-f03c-4d4c-b91f-3e096c487dfc.jpg";
    string image_name = file_name_absolute(image_path);
    ifstream in(image_path);
    std::stringstream buffer;
    buffer << in.rdbuf();
    std::string contents(buffer.str());

    httplib::Client cli(ip.c_str(), port);
    cli.set_timeout_sec(10);
    cli.set_read_timeout(10,20);
    httplib::MultipartFormDataItems items = {
        {"image", contents, image_name, "image/jpg"},
        {"picture_url", image_path, "", ""},
        {"wine_id", "0000001", "", ""}};
    auto res_insert = cli.Post("/insert", items);
    if (res_insert)
    {
        cout << res_insert->body << endl;
    }
    else
    {
        cout << "post occurs problem:" << endl;
    }
`
I want to post one image to server.  This code can really work in most times. But it failed when post some images. The image is ok and no error log throw.

**Comment by PixlRainbow** [comment] 2020-02-24 07:38
did you try opening the `ifstream` in binary mode?  
`ifstream in(image_path, ios::binary);`

**Comment by runningJ** [comment] 2020-02-24 11:39
Yes, I try it but also post failed.

**Comment by yhirose** [comment] 2020-02-24 16:29
@runningJ, if "This code can really work in most times" is true, I feel the problem is in the server that you are using. Could you try to do the same with curl to verify the problem really comes from httplib::Client? Thanks.

**Comment by yhirose** [comment] 2020-02-24 16:31
@runningJ, @runningJ, if "This code can really work in most times" is true, I feel the problem is in the server that you are using. Could you try to do the same with curl to verify the problem really comes from httplib::Client? I'll close it for now until you verify it. Thank for your understanding. Thanks!

**Closed by yhirose** 2020-02-24 16:31 UTC

**Comment by runningJ** [comment] 2020-02-25 02:50
Thank for you answer. Are there any restrictions on the size of uploaded images in the server.  This is my first time using your code as http server engine. @yhirose

**Comment by runningJ** [comment] 2020-02-25 02:58
my server code is

`Server server_obj; //http server obj
server_obj.Post("/search", [&](const auto &req, auto &res) {
        LOG(INFO) << "Get one search http request";
        auto ret = req.has_file("image");
        auto ret_number = req.has_file("search_number");
        try
        {
            if (ret && ret_number)
            {
                const auto &file = req.get_file_value("image");
                string img_content = file.content;
                const auto &search_number_file = req.get_file_value("search_number");
                string search_number = search_number_file.content;
                int search_n = stoi(search_number);
                string search_res = "";
                SearchImage(img_content, search_n, search_res);
                res.set_content(search_res.c_str(), "text/plain");
                //LOG(INFO)<<search_res;
            }
            else
            {
                LOG(ERROR) << "post parameter occurs problem";
                res.set_content("please check parameters", "text/plain");
            }
        }
        catch (...)
        {
            LOG(ERROR) << "search occurs problem and throw exception ...";
        }
    });
 cJSON *json_ip = cJSON_GetObjectItem(root, "ip");
    if (json_ip == nullptr)
    {
        LOG(ERROR) << "ip json not exists";
        exit(0);
    }
    std::string ip = json_ip->valuestring;

    cJSON *json_port = cJSON_GetObjectItem(root, "port");
    if (json_port == nullptr)
    {
        LOG(ERROR) << "port json not exists";
        exit(0);
    }
    int port = json_port->valueint;
    std::cout << "begin lisen port :" << ip << ":" << port << std::endl;
    server_obj.listen(ip.c_str(), port);
`

**Comment by runningJ** [comment] 2020-02-25 04:46
server endpoint parse req body is empty. I guess this may be a bug. @yhirose

**Comment by yhirose** [comment] 2020-02-25 13:39
'server endpoint parse req body is empty' is correct if the request is 'multipart/form-data' like your case. Each content in multipart form data item goes to `file.content` respectively.
https://github.com/yhirose/cpp-httplib/blob/3da925d6fe6f8255eecb06c58f3d31587404317a/test/test.cc#L822-L832

When it comes to the max size of receiving content is defined here:
https://github.com/yhirose/cpp-httplib/blob/3da925d6fe6f8255eecb06c58f3d31587404317a/httplib.h#L3202-L3207
So it depends on the value  from `std::string::max_size()` in your compiler.

'test/test.cc' has a number of examples regarding the multipart-form-data handling. You may first run the unit test suite to see whether the problem is really from cpp-httplib or not.

Thanks for your trying this library!
