### ISSUE TITLE
304 Not Modified response stalls until timeout

### ISSUE THREAD

**Issue by nickkelsey** [yhirose/cpp-httplib#1998] opened 2024-12-02 10:46 UTC
Testing with 0.13.3 as the client under Linux, Apache2 server.

If I add a If-Modified-Since, If-None-Match, or If-Range header the server may respond with 304 Not Modified. There is no body with a 304 response and no Content-Length header.

The httplib client stalls for almost exactly 5 seconds every time before returning the 304 status.

Suspect httplib is expecting a body to follow and the 5 second delay is my read timeout setting.

Feature request to please handle a 304 response as a no-body response, allowing the GET request to complete quickly and report the 304 status.

Thanks,

**Comment by yhirose** [comment] 2024-12-02 18:46
@nickkelsey do you think if it's also caused by the same reason as #1997? If so, can we close this issue?

**Closed** 2024-12-03 05:41 UTC
Labels: bug
