### ISSUE TITLE
Can't compile in VS2019 16.11.2

### ISSUE THREAD

**Issue by icegull** [yhirose/cpp-httplib#1049] opened 2021-09-14 01:48 UTC
I just pulled the newest code. So I can't compile now:
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2589	'(': illegal token on right side of '::'	WatchDog	D:\Project\backend_v11\inc\httplib.h	4463

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2062	type 'unknown-type' unexpected	WatchDog	D:\Project\backend_v11\inc\httplib.h	4463	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2059	syntax error: ')'	WatchDog	D:\Project\backend_v11\inc\httplib.h	4463	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2589	'(': illegal token on right side of '::'	WatchDog	D:\Project\backend_v11\inc\httplib.h	4512	

I thought it missed the include algorithm and limits. But I still can't compile it even I added them. So please fix it. Thank you very much

**Comment by icegull** [comment] 2021-09-14 01:50
The pulled commit is 3c522386e961d61768ea527d04713b5402356dd4.

**Comment by yhirose** [comment] 2021-09-17 15:23
@icegull, thanks for the report, I'll get back to this issue when I upgrade to 1.16.2 or later.

**Comment by rafalsk** [comment] 2021-09-22 13:07
any updates on this on the horizon of events?

**Comment by yhirose** [comment] 2021-09-22 20:02
@rafalsk, not yet. The problem is that the project that I am working depending on 16.10.2, and can't update to the latest for a while. If somebody work on it and send a pull request, that would be very much appreciated. Thanks for your understanding!

**Comment by estshorter** [comment] 2021-09-25 06:14
@icegull
I can build the following simple code using VS2019 v16.11.3.
What code did you build?
```cpp
#include "httplib.h"

int main(void) {
	// HTTP
	httplib::Server svr;

	svr.Get("/hi", [](const httplib::Request&, httplib::Response& res) {
		res.set_content("Hello World!", "text/plain");
		});
	svr.listen("0.0.0.0", 8080);


	// HTTP
	httplib::Client cli("http://cpp-httplib-server.yhirose.repl.co");
	auto res = cli.Get("/hi");
	res->status;
	res->body;
}
```

**Comment by estshorter** [comment] 2021-09-25 12:36
I'm not sure, but #1057 may fix this issue.

**Comment by yhirose** [comment] 2021-09-25 12:54
@icegull, @estshorter made sure that httplib can be compiled with v16.11.3. I'll close it.

**Closed by yhirose** 2021-09-25 12:54 UTC

**Comment by icegull** [comment] 2021-09-26 06:27
@yhirose Hi man. I confirm that I am able to compile now. Nice job!
