### ISSUE TITLE
body of POST request does not arriving to server in HTTPS 

### ISSUE THREAD

**Issue by SenseGuru** [yhirose/cpp-httplib#1362] opened 2022-08-18 04:08 UTC
Hi,

I am using cpp-httplib 0.10.9, VS 2022, OpenSSL 3-0-5 (pre compiled for Win64 from slproweb.com).

if (auto res = cli.Post(route_, headers, j_body ,"application/json"))
{   /// do something
}
where j_body is of type std::string.

it works well with http. But once the server is https  with #define CPPHTTPLIB_OPENSSL_SUPPORT. The body of the request "j_body" seems to not get into server which throws the error as if the body of request is blank. (Checked with Postman which replicates the exact error by placing a blank in the request body.)
Without HTTPS, everything works well on a local server.

GET requests work well in both http and https.

I tried the other POST overloaded method as follow: (which is just body in const char* type)
if (auto res = cli.Post(route_, headers, writable, j_body.size(), "application/json") )
which give the same error result output.

May I know what might be the issue?
Thanks
Richard

**Comment by yhirose** [comment] 2022-08-19 12:46
@SenseGuru, thanks for the report, but I am not sure why that happens on your machine. At least on my unit test suite, the following test works fine with SSL.

https://github.com/yhirose/cpp-httplib/blob/a9cf09795170a72372cbeb3feef3851b859c0e33/test/test.cc#L1717-L1721
https://github.com/yhirose/cpp-httplib/blob/a9cf09795170a72372cbeb3feef3851b859c0e33/test/test.cc#L2127-L2132

Could you provide more detailed information (like the HTTP request log on the server), so that I can reproduce it on my machine for debugging? Thanks!

**Comment by yhirose** [comment] 2022-08-21 22:27
I'll close it since there is little information.

**Closed by yhirose** 2022-08-21 22:27 UTC
Labels: need more information to verify
