### ISSUE TITLE
Poor performance on VPN

### ISSUE THREAD

**Issue by guteksan** [yhirose/cpp-httplib#424] opened 2020-04-10 15:06 UTC
Hi,
I have tested this library in terms of performance together with 4 other popular CPP REST libraries. The test was to trivially handle 200 POST messages sent from multiple producer threads. Among these 5 frameworks, httplib unfortunately stands out as the worst performing. Such a shame, as in my opinion it is the easiest to use of them all. Especially single threaded mode is quite bad. This is just to point you out this shortcoming I case you would like to investigate, as otherwise it is very nice library and if not the performance issue, I would pick it for my projects.

Here are some numbers (times in sec.ms or min:sec.ms) and rough test descriptions:

                 | Test 1 | Test 2 | Test 3  | Test 4
                 |--------|--------|---------|---------
    Restbed      | 28.112 | 23.739 | 225.659 | 8:20.430
    Restinio     | 26.311 | 24.625 | 223.159 | 8:20.410
    C++ Rest SDK | x      | 23.262 | 223.588 | x
    Pistache     | 22.725 | 22.782 | 227.106 | 8:52.729
    HttpLib      | 150.881| 42.465 | 244.281 | 9:38.554

Test 1 - Single working thread, direct reply with no work on server side, 5 producer threads
Test 2 - multithreaded (28 threads, HW concurrency), no work, 5 pr. th.
Test 3 - multithreaded (28 threads), simulated work (1s. duration), 5 pr. th.
Test 4 - multithreaded (4 threads), simulated work (1s.), 10 producer threads

**Comment by yhirose** [comment] 2020-04-10 15:56
@guteksan, fantastic report! I mainly focus on making this library cross platform, and giving an easy way to embed HTTP functionality to existing applications in my projects. Quite honestly, I haven't used this library in a serious server which requires high performance and expects lots of requests simultaneously. Sorry about that...

According to your benchmark, there must be a bottle neck(s) in the cpp-http server code. Is it possible for you to address functions which cause the performance problem in httplib.h by running on profiler or other performance measurement tool?

Also is it possible to put your benchmark test code in a repo on your github, so that I can also try the benchmark on my machine when I have time? I think it looks very useful and simple to setup.

Thanks!

**Comment by dorind** [comment] 2020-04-14 07:45
@yhirose I just ran over your library and used `SSLClient` for some json fetching and processing, both on linux and macos, after seeing this issue, I quickly ran a test with `valgrind` on linux and `SSLClient` is not even on the radar in terms of footprint, excellent work!

just as a side note, same code built both on linux and macos consumes ~9MB RAM on linux and ~7MB on macos

**Comment by yhirose** [comment] 2020-04-16 12:07
@dorind, thank for the feedback!
@guteksan, I am waiting your response. Thank you!

**Comment by guteksan** [comment] 2020-04-16 21:37
Hi,
Sorry, currently I have little time to prepare a deeper analysis. Maybe I'll find some at weekend. Anyway, what I discovered is that the performance is much affected by the network location of server and client machines. Above test results concern a case where the server and the client were physically in different networks, connected via VPN, also different OSes, but this should not matter. It looks like httplib introduces some constant processing overhead per request. But when the machines were physically in the same LAN, test results of all frameworks were similar, with httplib even slightly surpassing Pistache. It looks like the VPN situation had no effect on Restinio, slight effect on Pistache and significant efect on Httplib.

**Comment by yhirose** [comment] 2020-04-16 21:50
@guteksan, thanks for the detail. If you think the VPN situation affects the cpp-httplib performance, could you modify the title of this issue more specifically? 

Also if it's true, I just wonder how I can reproduce it because I probably cannot make the same environment. But at least if you can point to the line which causes the bad performance in cpp-htpplib, it would be very very helpful. Thanks for your help, but no rush!

**Comment by PixlRainbow** [comment] 2020-04-17 19:11
if the VPN produces the effect, I wonder if it has to do with packet sizes/buffers and tunneling, or resolving interfaces.

**Comment by yhirose** [comment] 2020-04-27 17:28
@guteksan, any update?

**Comment by yhirose** [comment] 2020-04-28 13:06
@guteksan, I can't work on the issue, since I don't have enough information to reproduce it at this point. SO I'll close it for now. But more detailed information are always welcome!

**Closed by yhirose** 2020-04-28 13:06 UTC
Labels: need more information to verify

**Comment by guteksan** [comment] 2020-05-28 11:00
Hi,
Sorry for late reply, I was busy with other things. Finally I got some time to prepare the analysis of performance of various REST frameworks, including Httplib, and provide the basic projects I used to run these tests:

https://github.com/guteksan/REST-CPP-benchmark

I hope this will help you find the bottleneck in the httplib library.

**Comment by apexlee79** [comment] 2022-06-04 14:42
in my LAN environment , it  spend close to 1s on very single request for 1 thread client, too slow  !
any root cause for this ?

**Comment by apexlee79** [comment] 2022-06-04 17:11
after some debug, it can be resolved by increasing the default ThreadPool number .
