### ISSUE TITLE
Need help with Windows 10 - Windows 7 compability issue

### ISSUE THREAD

**Issue by Lavalierre** [yhirose/cpp-httplib#783] opened 2020-12-04 14:01 UTC
This code works perfectly on the Windows 10, and doesn't work at all on Win7. Error code is 2 (Error::Connection). Can you help me fix this, or understand why this happens? I'm not too good at net programming

    
	httplib::Client cli( "http://rtsrr.beget.tech" );
	cli.set_connection_timeout( 30 );

	if ( auto res = cli.Get( "/current/info.json"  ) )
	{
		if ( res->status == 200 )
			print( "OK" );
	}
	else
	{
		print( res.error() );
	}

**Comment by yhirose** [comment] 2020-12-04 15:37
@Lavalierre, thanks for the report. You could check the code around the place where Error::Connection is set to see more detailed information.

I no longer have Windows 7, so I can't reproduce it and give you more meaningful information regarding this problem... But if you find anything about it, please let me know. Thanks for your help.

**Comment by Lavalierre** [comment] 2020-12-04 18:47
Ok, we tested it a bit, and found out which part of the code throws an Error::Connection. This one (line 2101):

`
if (sock != INVALID_SOCKET) {
    error = Error::Success;
  } else {
      if ( error == Error::Success ) { error = Error::Connection; }`

Interesting, that part of the code (line 2081) which is also throws an Error::Connection, is totally good and throws nothing. So it seemed problem in the socket creation, not connection. It might be the `socket_t create_socket` function. As I said, I'm not too strong at WinSock, so maybe this information could help you to figure it out. Thank you.

**Comment by yhirose** [comment] 2020-12-04 19:17
@Lavalierre, thanks for the info. Could you take a look at lines 1930, 1957, 1960, 1983 in `create_socket` to see where the INVALID_SOCKET is set? You might find more information from #292 as well. Thanks!

**Comment by Lavalierre** [comment] 2020-12-04 19:35
Aight, it seems line 1930 throws an INVALID_SOCKET

**Comment by yhirose** [comment] 2020-12-04 20:56
@Lavalierre, it seems like your Windows 7 has a network problem. Could you try to run the following example? It should print `ret: 0`, if the network is good on your Windows 7. Thanks!

```cpp
#include <winsock2.h>
#include <ws2tcpip.h>
#pragma comment(lib, "ws2_32.lib")

#include <iostream>
#include <string>

int main() {
    WSADATA wsaData;
    WSAStartup(0x0002, &wsaData);

    const char *host = "google.com";
    int port = 80;
    auto service = std::to_string(port);

    struct addrinfo hints;
    memset(&hints, 0, sizeof(struct addrinfo));
    hints.ai_family = AF_UNSPEC;
    hints.ai_socktype = SOCK_STREAM;

    struct addrinfo *result;
    auto ret = getaddrinfo(host, service.c_str(), &hints, &result);
    std::cout << "ret: " << ret << std::endl;

    freeaddrinfo(result);
    WSACleanup();
    return 0;
}
```

```
D:\>cl /EHsc a.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29334 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

a.cpp
Microsoft (R) Incremental Linker Version 14.28.29334.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:a.exe
a.obj

D:\>a.exe
ret: 0
```

**Comment by Lavalierre** [comment] 2020-12-05 00:34
Nope, it can't be, because this tested by 4 people on 4 different machines. But ok, I'll send them this too.

**Comment by yhirose** [comment] 2020-12-05 00:37
@Lavalierre, thanks. Since it's not directly related to httplib.h, I'll close it for now until I get a further evidence. Hope the example will help you figure out the cause of the problem!

**Closed by yhirose** 2020-12-05 00:37 UTC
