### ISSUE TITLE
[Bug] Can't upload file to VirusTotal

### ISSUE THREAD

**Issue by sccoouut** [yhirose/cpp-httplib#1162] opened 2022-01-12 18:14 UTC
Hi, i'm using VirusTotal API in order to check is file malware, so I need to upload file. I tried to do it in that way, but it have not succeeded:
```
httplib::Client cli("https://www.virustotal.com");

httplib::Headers headers{
	{ "Accept", "text/plain" },
	{ "Content-Type", "application/x-www-form-urlencoded" }
};
httplib::MultipartFormDataItems items{
	{ "apikey", api_key, "", "" },
	{ "file", std::string(buffer.begin(), buffer.end()), file_name, ""}
};

auto res = cli.Post("/vtapi/v2/file/scan", headers, items);
```
**The error that I get is: "Write (5)"**
I tried to do it also in another way and it have not worked too:
```
httplib::Client cli("https://www.virustotal.com");

httplib::Headers headers{
	{ "Accept", "text/plain" },
	{ "Content-Type", "application/x-www-form-urlencoded" }
};
httplib::Params params{
	{ "apikey", std::string(api_key) },
	{ "file", "data:name=" + std::string(file_path) + ";base64," + encoded }
};

auto res = cli.Post("/vtapi/v2/file/scan", headers, params);
```
Although, I tried to use curl lib and it works great, there is a working code:
```
auto params = "apikey=" + std::string(api_key) + "&file=data:name=" + std::string(file_path) + ";base64," + encoded;

CURL* hnd = curl_easy_init();
curl_easy_setopt(hnd, CURLOPT_CUSTOMREQUEST, "POST");
curl_easy_setopt(hnd, CURLOPT_URL, "https://www.virustotal.com/vtapi/v2/file/scan");
struct curl_slist* headers = NULL;
headers = curl_slist_append(headers, "Accept: text/plain");
headers = curl_slist_append(headers, "Content-Type: application/x-www-form-urlencoded");
curl_easy_setopt(hnd, CURLOPT_HTTPHEADER, headers);
curl_easy_setopt(hnd, CURLOPT_POSTFIELDS, params.c_str());
std::string readBuffer;
curl_easy_setopt(hnd, CURLOPT_WRITEFUNCTION, WriteCallback);
curl_easy_setopt(hnd, CURLOPT_WRITEDATA, &readBuffer);
CURLcode ret = curl_easy_perform(hnd);
curl_easy_reset(hnd);
```
Am I doing something wrong?

**Comment by PixlRainbow** [comment] 2022-01-13 14:20
did you compile httplib with openssl enabled?

**Comment by sccoouut** [comment] 2022-01-13 16:32
yep. it even worked with small file, but with big files it does not work

**Comment by yhirose** [comment] 2022-01-14 01:53
> it even worked with small file, but with big files it does not work

If it works with a small file, I don't think it's a problem of cpp-httplib, but you simply hit a size limit on the service that you are using. Could you verify that?

**Comment by sccoouut** [comment] 2022-01-14 07:05
> > it even worked with small file, but with big files it does not work
> 
> If it works with a small file, I don't think it's a problem of cpp-httplib, but you simply hit a size limit on the service that you are using. Could you verify that?

The second file has worked with the cURL library.

**Comment by yhirose** [comment] 2022-01-14 12:18
@sccoouut, could you give me more detailed information about the 'second file'?

**Comment by sccoouut** [comment] 2022-01-14 12:43
> @sccoouut, could you give me more detailed information about the 'second file'?

The first file (that worked) is .txt file with one word. The second file is [cpuminer](https://github.com/pooler/cpuminer) last release. I have tested my code on Windows 10 with MSVC and VS22 (the httplib and needed depends I have install with vcpkg).

**Comment by yhirose** [comment] 2022-01-14 17:34
@sccoouut, I am actually concerned with the size of the second file, not the type of it. Could you figure out **the minimum size** that can cause the problem, so that I could easily reproduce it on my machine.

Could you also give more detail about the difference between the actual HTTP request data from cpp-httplib and the one from cURL? (You can get the info with `Client::set_logger`. As for CURL, I think you can use the command-line version of curl with option `-v`.)
https://github.com/yhirose/cpp-httplib/blob/65a8f4cf44195d6d042c9ed0a174c9c8ea0a1b05/httplib.h#L1030

Thanks a lot!

**Comment by yhirose** [comment] 2022-01-19 23:46
any response?

**Comment by sccoouut** [comment] 2022-01-21 16:31
Hi, I have been a little bit busy on the last week, I'll do it in few next days.

**Comment by yhirose** [comment] 2022-02-09 23:34
Close it until further information is provided.

**Closed by yhirose** 2022-02-09 23:34 UTC
Labels: need more information to verify

**Comment by sccoouut** [comment] 2022-02-15 13:11
When I'm trying to install logger on my client, it's not being called. Am I doing something wrong?
```
void logger( const httplib::Request &request, const httplib::Response &response ) {
	std::cout << request.body << std::endl;
}

std::ifstream file( file_path, std::ios::binary );
std::vector<uint8_t> file_data( std::istreambuf_iterator<char>( file ), {} );
file.close();

httplib::Client cli( "https://www.virustotal.com" );
cli.set_logger( logger );
httplib::Headers headers{
	{ "Accept", "text/plain" },
	{ "Content-Type", "application/x-www-form-urlencoded" }
};
httplib::MultipartFormDataItems items{
	{ "apikey", api_key, "", "" },
	{ "file", std::string( file_data.begin(), file_data.end() ), file_name, "" } 
};

auto res = cli.Post( "/vtapi/v2/file/scan", headers, items );
std::cout << res->body << std::endl;
```

**Comment by sccoouut** [comment] 2022-02-16 19:57
@yhirose

**Comment by yhirose** [comment] 2022-02-16 22:01
Working example:

```cpp
#include <httplib.h>
#include <iostream>

int main(void) {
  httplib::Client cli("https://httpbin.org");

  cli.set_logger([](const httplib::Request &req, const httplib::Response &res) {
    std::cout << req.body << std::endl;
    std::cout << res.body << std::endl;
  });

  auto res = cli.Post("/post", "hello world!", "text/plain");
}
```

Result:

```
hello world!
{
  "args": {},
  "data": "hello world!",
  "files": {},
  "form": {},
  "headers": {
    "Accept": "*/*",
    "Content-Length": "12",
    "Content-Type": "text/plain",
    "Host": "httpbin.org",
    "User-Agent": "cpp-httplib/0.10.2",
    "X-Amzn-Trace-Id": "Root=1-620d740b-194db0ce619499692cbca2a1"
  },
  "json": null,
  "origin": "208.74.141.25",
  "url": "https://httpbin.org/post"
}
```

**Comment by PixlRainbow** [comment] 2022-02-17 02:58
There is a problem. If there is a connection failure, logger will not be called because `ClientImpl::process_request` will return immediately (before it reaches the logger call):
https://github.com/yhirose/cpp-httplib/blob/bb00a23116f5c9f64f1e257ecf5b97a49d0be44e/httplib.h#L6354-L6435

**Comment by yhirose** [comment] 2022-02-17 04:56
@PixlRainbow, thanks for the clarification. Yes, when a connection error happens, the logger won't be called, since the logger is HTTP level logger.

@sccoouut, hope @PixlRainbow's comment helps you understand the situation. TCP/IP level error logger isn't available, yet. (#870)

**Comment by PixlRainbow** [comment] 2022-02-17 06:07
it also makes it impossible to identify what the difference is between httplib's request data and curl's request data that makes the virustotal request fail
