### ISSUE TITLE
The timing of the client request is more than 50 milliseconds slower than that of the server

### ISSUE THREAD

**Issue by Microkitty** [yhirose/cpp-httplib#614] opened 2020-08-19 02:12 UTC
1.The network between client and server is normal without delay.
2.Client timing is from sending request to receiving response, while server timing is from receiving request to sending response.
3.Under the same network environment, the latency of Python client and server is only 10 ms.
4.The delay of accessing httplib server with Python client is also more than 50 ms.

**Comment by yhirose** [comment] 2020-08-19 04:44
@Microkitty, thanks for the feedback. How did you measure it?

**Comment by Microkitty** [comment] 2020-08-19 06:04
@yhirose The server is on a Linux server and the client is on another windows PC, Linux and PC plug in the same route.

**Comment by yhirose** [comment] 2020-08-19 12:15
@Microkitty, I mean how to measure the time '50 ms' and '10 ms'. On client side, did you use the unix `time` command or something? How about server side? Also does it ALWAYS take the 50 ms regardless whether you use Windows, Linux or other OSs? Thanks for providing me the detail!

**Comment by Microkitty** [comment] 2020-08-20 00:56
@yhirose gettimeofday() is used for service timing on Linux server, and QueryPerformanceFrequency() is used for client timing on PC.

**Comment by yhirose** [comment] 2020-08-20 01:35
@Microkitty, just one more question please. If you have both the client and the httplib server on the same Linux machine, do you still observe the 50ms latency, or quicker? Thanks!

**Comment by Microkitty** [comment] 2020-08-20 06:00
@yhirose Only when the client is on Windows, 50ms will appear.
If the client and the httplib server on the same or not same Linux machine, it doesn't appear.

**Comment by yhirose** [comment] 2020-08-20 22:40
@Microkitty, I don't have both Linux and Windows machine in a same network... So when I have time this weekend, I'll try to reproduce it with a Windows machine having a Ubuntu on VirtualBox, and run a httplib server on the Windows and send a request from a Python script on the Ubuntu. Could you show me your Python client code to measure the performance? Thanks for your help!

**Comment by Microkitty** [comment] 2020-08-21 01:33
@yhirose httplib server on Linux and httplib::Client on Windows will take 50ms, not the other way around.

**Comment by yhirose** [comment] 2020-08-21 01:37
@Microkitty, sorry for my misunderstanding. I should have said "run a httplib server on the Ubuntu on the VirtualBox and send a request from a Python script on the Windows"... Is it possible for you to get me your python script including the measurement code?

**Comment by Microkitty** [comment] 2020-08-21 01:53
@yhirose 
import requests
import time

url = "http://192.168.2.186:8080/index"
data = "Client python"
start_time = time.time()
res = requests.post(url=url,data=data)
end_time = time.time()
print (int(round((end_time - start_time) * 1000)),"ms")
print(res.text)

**Comment by yhirose** [comment] 2020-08-24 20:28
I'll close it for now since the both options work for me.

**Closed by yhirose** 2020-08-24 20:28 UTC
