### ISSUE TITLE
One test fails on FreeBSD: SpecifyServerIPAddressTest.RealHostname_Online

### ISSUE THREAD

**Issue by yurivict** [yhirose/cpp-httplib#1339] opened 2022-07-30 16:40 UTC
```
test.cc:821: Failure
Expected equality of these values:
  Error::Connection
    Which is: Connection (2)
  res.error()
    Which is: SSLConnection (8)
[  FAILED  ] SpecifyServerIPAddressTest.RealHostname_Online (10 ms)
```

**Comment by yhirose** [comment] 2022-07-30 16:56
@yurivict, thanks for the report, but these kind of errors are caused by the environment where the unit test suite is running, not by cpp-httplib. You can see a number of similar reports in the past issues. I'll close it for now until there is a clear evident that the connection problems are really caused by cpp-httplib. Thanks for you understanding!

**Closed by yhirose** 2022-07-30 16:56 UTC

**Comment by yurivict** [comment] 2023-06-11 04:02
@yhirose 

There is a new error now:
```
[ RUN      ] MultipartFormDataTest.LargeData
test.cc:5427: Failure
Expected equality of these values:
  200
  res->status
    Which is: 413
[  FAILED  ] MultipartFormDataTest.LargeData (1037 ms)
```
Is this also caused by the environment?

**Comment by yhirose** [comment] 2023-06-11 08:23
@yurivict, what is`CPPHTTPLIB_PAYLOAD_MAX_LENGTH` value on your machine?

**Comment by yurivict** [comment] 2023-06-11 16:31
```CPPHTTPLIB_PAYLOAD_MAX_LENGTH=18446744073709551615```

**Comment by yhirose** [comment] 2023-06-11 22:22
413 can be set only at line 3865 or 5610. Which one is hit?

**Comment by yurivict** [comment] 2023-06-12 00:56
It doesn't cross any of the above mentioned lines.
I've added printouts next to each of these 2 lines and these printouts were never triggered during this case:
```
[ RUN      ] MultipartFormDataTest.LargeData
test.cc:5431: Failure
Expected equality of these values:
  200
  res->status
    Which is: 413
[  FAILED  ] MultipartFormDataTest.LargeData (1039 ms)
```

**Comment by yurivict** [comment] 2023-07-10 02:35
The version 0.13.1 has 5 failing tests:
```
[  FAILED  ] 5 tests, listed below:
[  FAILED  ] SpecifyServerIPAddressTest.RealHostname_Online
[  FAILED  ] ServerTestWithAI_PASSIVE.GetMethod200
[  FAILED  ] MultipartFormDataTest.LargeData
[  FAILED  ] MultipartFormDataTest.PostCustomBoundary
[  FAILED  ] MultipartFormDataTest.PutFormData
```
