### ISSUE TITLE
Response time is more when requested in a loop

### ISSUE THREAD

**Issue by Hari-Muniganti** [yhirose/cpp-httplib#502] opened 2020-05-28 14:45 UTC
I am using httplib for my application. When i send a request from client it is taking 45milliseconds on an average to get response. But when i tried to send 10 same requests in a loop it is taking 7-8seconds to get all the responses. Where is it going wrong?

Thanks

**Comment by yhirose** [comment] 2020-05-28 16:45
@Hari-Muniganti, thank you for the feedback. But it's too little information for me to answer. Could you give your smallest possible code that can reproduce the problem, then I may be able to answer your question. Thanks!

**Comment by PixlRainbow** [comment] 2020-05-29 07:20
note that some third party servers may intentionally rate-limit clients that send requests too quickly as a form of DDoS protection

**Comment by yhirose** [comment] 2020-05-31 14:35
@Hari-Muniganti, please see @PixlRainbow's comment. If you still think this problem is caused by cpp-httplib server, could you give me more detailed information as I said in my previous comment?  I'll close it for now. Thanks!

**Closed by yhirose** 2020-05-31 14:35 UTC
Labels: need more information to verify
