### ISSUE TITLE
Memory leak in the upload example

### ISSUE THREAD

**Issue by tietzedk** [yhirose/cpp-httplib#1084] opened 2021-11-02 14:37 UTC
When using the upload example and you upload a larger jpeg image e.g. 5MB, several times, the memory size of the upload process will start increase each time you upload the image. This does not happen the first time you upload a image.

**Comment by yhirose** [comment] 2021-11-02 15:38
@tietzedk, could you provide more detailed information?

**Comment by tietzedk** [comment] 2021-11-03 08:14
Get the latest source
git clone https://github.com/yhirose/cpp-httplib.git
cd cpp-httplib/example/
make

Start the upload example by using "./upload"

Download a test image from e.g. https://www.learningcontainer.com/sample-jpeg-file-download-for-testing/ to the local device. I use the 5MB test image for this test.

Open the chrome browser and type http://localhost:1234 in the address bar.

Select the test image from the local device and press "Send"

Monitor the "RSS" memory size of the process by using "ps aux"

Monitor the RSS size of the upload process
      PID  %CPU %MEM    VSZ         **RSS**     TTY    STAT START   TIME COMMAND
     14665  0.0     0.0     217168  **7032**  pts/1    Sl+  08:56   0:00 ./upload <- just after start
     14665  0.0     0.0     348240  **7032**  pts/1    Sl+  08:56   0:00 ./upload <- after load of page
     14665  0.0     0.0     413776  **7356**  pts/1    Sl+  08:56   0:00 ./upload <- after 1. image upload
     14665  0.0     0.0     479312 **19760** pts/1    Sl+  08:56   0:00 ./upload <- after 2. image upload
     14665  0.0     0.0     544848 **32692** pts/1    Sl+  08:56   0:00 ./upload <- after 3. image upload
     14665  0.0     0.0     610384 **45096** pts/1    Sl+  08:56   0:00 ./upload <- after 4. image upload

The RSS size will grow after each upload

**Comment by yhirose** [comment] 2021-11-04 20:00
@tietzedk, thanks for the details!

**Comment by zhangyuhu** [comment] 2021-12-02 09:44
Supplement:
Since I am also using this project now, I also tested it 。I use the script to send and use the script to monitor the RSS, and found that the memory will stabilize and not increase after a period of time 。
this is send script :

#!/bin/bash

while :; do
  curl --location --request POST 'http://0.0.0.0:1234/post' \
    --form 'image_file=@"./Sample-Image-file-Download.jpg"'
done


this is monitor script :

#!/bin/bash
_PID=$1
_TMP=$(pwd)/$_PID.tmp
touch $_TMP
while true
do
    if [ -f /proc/$_PID/status ]; then
        cat /proc/$_PID/status > $_TMP
        _VMRSS=`cat $_TMP | grep VmRSS | awk '{print $2}'`
        echo " " ${_VMRSS}
    fi
    sleep 1
done

**Comment by yhirose** [comment] 2021-12-02 12:58
@zhangyuhu, thank you for the fine report!
@tietzedk, do you have any thought on @zhangyuhu's comment?
Thanks!

**Comment by yhirose** [comment] 2021-12-04 12:24
@tietzedk, according to @zhangyuhu's comment, is it just an issue of the way of OS or C++ standard library memory management? Anyway, I'll take a look at it when I am not busy in the future.

**Comment by yhirose** [comment] 2021-12-07 14:01
@tietzedk, one thing that I noticed is that the following line increases memory usage. But even when the `MultipartFormDataParser` object is destructed including `buf_`, the memory usages stays... It seems like it's due to the memory management strategy of std::string, and there is nothing to do on our side...

Do you feel that it's a really memory leak caused by cpp-httplib, or we can't say it's a memory leak because the memory usage eventually will stabilize as @zhangyuhu observed?

https://github.com/yhirose/cpp-httplib/blob/824e7682e4d95e1bb21e501731eb2b6bb23033d2/httplib.h#L3666

**Comment by tietzedk** [comment] 2021-12-07 14:33
@yhirose My application is running on an embedded Linux board with 256MB of memory and files are uploaded several times a day. 

I my setup, the memory usage never stabilizes, and the web backend process is killed by the oom_killer. 

I have implemented a workaround where the "Server” instance is inside an endless loop and POST handler will call the stop method after a file upload. The call of the stop method will cause the server instance to get out of scope and this will release the memory. This workaround is not perfect since the backend will be offline for a short interval while restarting the server instance, but it is much faster than restarting the whole process.

**Comment by yhirose** [comment] 2021-12-15 03:57
@tietzedk, as @zhangyuhu mentioned, the memory usage goes up with the first several uploads and stop increasing after that. I tested with a 4.9MB jpeg file on my Intel iMac 2017. In this case, RES stops at 20868.

![image](https://user-images.githubusercontent.com/357397/146120169-374193f0-8886-4eb1-9b9d-f38cbf07e050.png)

I'll try to reproduce it, but it's really hard. Is it related to the particular operating system that you are running on?

**Comment by yhirose** [comment] 2021-12-18 04:37
I made some performance improvement to avoid `buf_.append()` and `buf_erase()`. On my Intel iMac 2017, it reduces memory usage a tiny bit... After a few uploads, the memory usages stays at 20620, and never goes up afterward. So no memory leak occurs.

![image](https://user-images.githubusercontent.com/357397/146628806-25114e1a-6608-4393-9fde-89d58f6f7da7.png)

Here is my test driver code:

https://github.com/yhirose/cpp-httplib/blob/bc3e0989646ea5db410ce6f528a3678324aaa2ad/example/uploader.sh#L1-L6

So I close this issue for now until I receive an evidence that cpp-httplib really causes memory leak.

**Closed by yhirose** 2021-12-18 04:37 UTC
Labels: need help, need more information to verify

**Comment by homer6** [comment] 2022-08-01 16:21
I'm running into this too. Memory usage continues to climb for an upload of 20MB for this route:

```
        http_server.Post("/testpost", [&]( const httplib::Request& request, httplib::Response& response ){

            response.set_content( "test post", "application/json" );

        });
```

**Comment by homer6** [comment] 2022-08-01 20:02
@yhirose Can we reopen this please? I'm trying to troubleshoot still. Valgrind came back clean so far.

**Comment by homer6** [comment] 2022-08-01 20:14
Memory usage persists beyond the lifetime of `httplib::Server http_server;` I ran the server twice (with http_server.stop() after the first `listen` run and the memory allocations from all requests existed during the second lifetime.

**Comment by homer6** [comment] 2022-08-01 20:34
It looks like heap fragmentation. Although there isn't a memory leak, it keeps expanding the RSS. If you use the valgrind massif tool, you'll be able to see it too. This post explains it in detail: https://stackoverflow.com/a/23079262/278976

**Comment by homer6** [comment] 2022-08-01 20:37
If I'm right, then this may only show up with large upload sizes. The file that I'm using to upload is 21MB.

**Comment by homer6** [comment] 2022-08-02 02:21
Tested it with a 19KB. It did the same thing until about 14MB of RSS, where it stabilized. Also, after repeated uploads (about 50), the 21MB upload did finally stabilize at 1.42GB RSS.

**Comment by homer6** [comment] 2022-08-02 03:08
I'm certain now. Valgrind massif clearly shows that it's the allocations inside of `Server::read_content(Stream &strm, Request &req, Response &res)`.

**Comment by yhirose** [comment] 2022-08-06 16:21
@homer6, thanks for the excellent research! Could you dig into the situation a bit deeper? I would like to know which C++ Standard library call affects the memory usage.
