### ISSUE TITLE
Client request get stuck

### ISSUE THREAD

**Issue by AMBER17** [yhirose/cpp-httplib#596] opened 2020-08-01 13:36 UTC
Hello,
I encounter an error when sending requests from a Chinese server to European servers (high latency).
Most of time the queries finish correctly or the library returns a nullptr, but sometimes the program gets stuck on the execution of the query without ever having a return (> 45min stuck, then I have a failsafe thread that restart my prog).
My program is running on thousands of European servers, no problem. 
I only encounter the problem on Chinese servers so with high latency.
I am using SSLClient with the default timeouts.
Any idea?

**Comment by yhirose** [comment] 2020-08-01 14:55
@AMBER17, thank you for the feedback. I probably can't give you any help because I can't reproduce your environment. Anyway, I suggest you to check wity `curl -v YOUR_URL` to see what curl says for this situation. Sorry about that...

**Comment by AMBER17** [comment] 2020-08-01 15:38
I'm running on Windows virtual machine low perf (1300mb ram, 1vCPU).
I tried to override the timeout (connection, read, write) and the problem still happens.
You don't have any clues on where inside the code it can be stuck (infinite loop) ?
I can maybe help out for debugging but I currently have no idea where it can be stuck.

**Comment by yhirose** [comment] 2020-08-01 16:19
No, I don't have any clue. That's why I suggested you to send the same request with curl (or cpr) to see if it's a cpp-httplib specific problem or a general that can happen with any tool.

Since it's my after-work personal project, I don't basically have time to support others and can do debugging only if I can reproduce on my machine with a smallest possible code snippet. Thank you for your understanding!

**Comment by yhirose** [comment] 2020-08-01 18:25
I close it for now. But I'll reopen it whenever I am given a code snippet that I can reproduce the problem on my machine. Thanks!

**Closed by yhirose** 2020-08-01 18:25 UTC
