### ISSUE TITLE
I don't think [issues-937] has been solved.

### ISSUE THREAD

**Issue by guoxiangzhou** [yhirose/cpp-httplib#943] opened 2021-05-20 06:27 UTC
I don't think the problem has been solved.

I debugged the test code: The reason why it can exit normally is that Before the t_ thread enters the listen function, the main thread executes the teardown function.

In general, The t_ thread is waiting for the accpet function to return, and t_. join() will block

_Originally posted by @guoxiangzhou in https://github.com/yhirose/cpp-httplib/issues/937#issuecomment-843827283_

**Comment by yhirose** [comment] 2021-05-20 12:34
Duplicate of #937

**Closed by yhirose** 2021-05-20 12:34 UTC
