### ISSUE TITLE
 Couldn't resolve host name

### ISSUE THREAD

**Issue by azchatlanin** [yhirose/cpp-httplib#1884] opened 2024-07-19 09:17 UTC
There are two docker containers. Both are on the same network. 
When I make a post request from the first to the second, everything is fine. But if the second container is disabled, the first one crashed during the execution of the post request. (exited with code 0)

When I do the same thing, but using curl. curl throw an exception:

I would like to be able to intercept this exception, and not completely crushed the docker.

```yml
services:
  service_1:
    image: image
    container_name: service_1
    environment:
     - USER_UID=1000
     - USER_GID=1000
       #restart: always
    networks:
      - service_net

networks:
  service_net:
    external: true
```

```cpp
// base request with httplib
httplib::Client m_cli { "service_2:5000" };


httplib::Headers headers = {
  { "Content-Type", "application/json" }
};

try
{
   auto r = m_cli.Post("/", headers, payload.dump(), "application/json" );
   log(r->status);
}
catch(...)
{
   log("error");
}
// dont catch error
// docker container exited with code 0

```

```cpp
// base curl
CURL *curl;
CURLcode res;

curl = curl_easy_init();
if (curl) {
  curl_easy_setopt(curl, CURLOPT_URL, "service_2:5000");
      
  struct curl_slist *headers = NULL;
  headers = curl_slist_append(headers, "Content-Type: application/json");
  curl_easy_setopt(curl, CURLOPT_HTTPHEADER, headers);
  curl_easy_setopt(curl, CURLOPT_POSTFIELDS, "param1=value1&param2=value2");

  res = curl_easy_perform(curl);
  if (res != CURLE_OK)                        <--- here i can catch error. docker container dont exited
  { 
    std::cerr << "curl_easy_perform() failed: " << curl_easy_strerror(res) << std::endl;
  }

  curl_easy_cleanup(curl);
  curl_slist_free_all(headers);
}
```

**Comment by yhirose** [comment] 2024-08-30 00:09
@azchatlanin sorry for the late replay. Could you show me the smallest example (server code and client code, and Dockerfile files for each, and docker compose yaml) to reproduce this problem? Then, I'll take a look at it. Thanks!

**Comment by yhirose** [comment] 2024-08-31 23:25
@azchatlanin I made to test code to reproduce it on my machine, but I am not able.

You can test in [this branch] with the following command.

```bash
$ docker compose -f docker-compose-issue1884.yml up
...
[+] Running 1/0
 ✔ Container cpp-httplib-client-1  Created                                                           0.0s
Attaching to client-1
client-1  | ### cpp-httplib client test...
client-1  | Could not establish connection (2)
client-1 exited with code 0
```

I'll close it for now since I am not able to reproduce it. Thanks!

**Closed by yhirose** 2024-08-31 23:25 UTC
Labels: need more information to verify
