### ISSUE TITLE
This lib does not work on linux (debian)

### ISSUE THREAD

**Issue by how0723** [yhirose/cpp-httplib#79] opened 2018-06-16 10:01 UTC
This lib does not work on linux (debian)
I make a project to set up a http-server,
but it does not work
why

**Comment by DJuego** [comment] 2018-06-16 10:27
Hi!  I think you should better explain your problem. The more relevant details give you better chances of fixing your problem.

In order to identify the problem you should post a **complete and minimal code** than reproduces the initial problem.

It is important that:

-     the code is complete, so people can test it
-     the code is as simple as possible, the best is one main() with all the code inside -- people don't want to setup a complex project just to test your code
-     the code reproduces the initial problem
-     the application doesn't depend on external resource files (unless it's related to the problem)
- 

You must explain what you expected to happen and what really happens. the code crash? Is there an error message? What message?

I hope these tips can help you improve the quality of your issues. Sorry for my English. 

DJuego

**Comment by yhirose** [comment] 2018-06-16 12:29
@DJuego, thank you for the valuable information which helps a lot both users and developers!

@how0723, please describe the problem on your machine clearly according to the @DJuego's suggestion. I actually confirmed all 54 unit tests passed successfully on the latest Debian based Ubuntu 18.04 LTS server. (on VirtualBox on MacOS.) Thanks!

**Comment by how0723** [comment] 2018-06-17 02:10
here is my code , is the sample code
and it can work on windows , but just can not work on debian

//
//  simplesvr.cc
//
//  Copyright (c) 2013 Yuji Hirose. All rights reserved.
//  The Boost Software License 1.0
//

#include <httplib.h>
#include <cstdio>
#include <iostream>

#define SERVER_CERT_FILE "./cert.pem"
#define SERVER_PRIVATE_KEY_FILE "./key.pem"

using namespace httplib;
using namespace std;

string dump_headers(const Headers& headers)
{
    string s;
    char buf[BUFSIZ];

    for (const auto& x: headers) {
       snprintf(buf, sizeof(buf), "%s: %s\n", x.first.c_str(), x.second.c_str());
       s += buf;
    }

    return s;
}

string dump_multipart_files(const MultipartFiles& files)
{
    string s;
    char buf[BUFSIZ];

    s += "--------------------------------\n";

    for (const auto& x: files) {
        const auto& name = x.first;
        const auto& file = x.second;

        snprintf(buf, sizeof(buf), "name: %s\n", name.c_str());
        s += buf;

        snprintf(buf, sizeof(buf), "filename: %s\n", file.filename.c_str());
        s += buf;

        snprintf(buf, sizeof(buf), "content type: %s\n", file.content_type.c_str());
        s += buf;

        snprintf(buf, sizeof(buf), "text offset: %lu\n", file.offset);
        s += buf;

        snprintf(buf, sizeof(buf), "text length: %lu\n", file.length);
        s += buf;

        s += "----------------\n";
    }

    return s;
}

string log(const Request& req, const Response& res)
{
    string s;
    char buf[BUFSIZ];

    s += "================================\n";

    snprintf(buf, sizeof(buf), "%s %s %s", req.method.c_str(), req.path.c_str(), req.version.c_str());
    s += buf;

    string query;
    for (auto it = req.params.begin(); it != req.params.end(); ++it) {
       const auto& x = *it;
       snprintf(buf, sizeof(buf), "%c%s=%s",
           (it == req.params.begin()) ? '?' : '&', x.first.c_str(), x.second.c_str());
       query += buf;
    }
    snprintf(buf, sizeof(buf), "%s\n", query.c_str());
    s += buf;

    s += dump_headers(req.headers);
    s += dump_multipart_files(req.files);

    s += "--------------------------------\n";

    snprintf(buf, sizeof(buf), "%d\n", res.status);
    s += buf;
    s += dump_headers(res.headers);

    return s;
}

int main(int argc, const char** argv)
{
    if (argc > 1 && string("--help") == argv[1]) {
        cout << "usage: simplesvr [PORT] [DIR]" << endl;
        return 1;
    }

#ifdef CPPHTTPLIB_OPENSSL_SUPPORT
    SSLServer svr(SERVER_CERT_FILE, SERVER_PRIVATE_KEY_FILE);
#else
    Server svr;
#endif

    svr.Post("/multipart", [](const auto& req, auto& res) {
        auto body =
            dump_headers(req.headers) +
            dump_multipart_files(req.files);

        res.set_content(body, "text/plain");
    });

    svr.set_error_handler([](const auto& /*req*/, auto& res) {
        const char* fmt = "<p>Error Status: <span style='color:red;'>%d</span></p>";
        char buf[BUFSIZ];
        snprintf(buf, sizeof(buf), fmt, res.status);
        res.set_content(buf, "text/html");
    });

    svr.set_logger([](const auto& req, const auto& res) {
        cout << log(req, res);
    });

    auto port = 8080;
    if (argc > 1) {
        port = atoi(argv[1]);
    }

    auto base_dir = "./";
    if (argc > 2) {
        base_dir = argv[2];
    }

    svr.set_base_dir(base_dir);

    cout << "The server started at port " << port << "...";

    svr.listen("localhost", port);

    return 0;
}

**Comment by how0723** [comment] 2018-06-17 02:12
when I excute the code , there is not any reply

**Comment by yhirose** [comment] 2018-06-17 02:28
Could you tell me the compiler and compile options that you are using?
Thanks.

**Comment by how0723** [comment] 2018-06-17 02:31
this is my cmakelist file

# set minimum cmake version
cmake_minimum_required(VERSION 3.0)
project(network-test)

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${PROJECT_BINARY_DIR}/bin)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${PROJECT_BINARY_DIR}/lib)
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${PROJECT_BINARY_DIR}/lib)

set (CHTX_PR_ALG_VERSION_MAJOR 1)
set (CHTX_PR_ALG_VERSION_MINOR 0)

# c++11 required

if(CMAKE_HOST_UNIX)
	set( CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++14 -pthread" )
endif(CMAKE_HOST_UNIX)

option (USE_RAPIDJSON  "USE RAPIDJSON LIB" ON) 

if (USE_RAPIDJSON)
	include_directories ("${CMAKE_CURRENT_SOURCE_DIR}/3rdparty")
endif (USE_RAPIDJSON)

if(CMAKE_HOST_WIN32)
	ADD_DEFINITIONS(-DWIN32)
	ADD_DEFINITIONS(-D_WINDOWS)
	ADD_DEFINITIONS(-D_CRT_SECURE_NO_WARNINGS)
endif(CMAKE_HOST_WIN32)	

include_directories(include)

set(SIMPLE_SERVER_TEST_SOURCE_FILES 
	src/simplesvr/simplesvr.cpp
)
set(SIMPLE_SERVER_TEST_HEADER_FILES
	include/httplib.h
)

if(CMAKE_HOST_WIN32)
	link_libraries(ws2_32)
endif(CMAKE_HOST_WIN32)	

add_executable("simple-server" ${SIMPLE_SERVER_TEST_SOURCE_FILES} ${SIMPLE_SERVER_TEST_HEADER_FILES})

**Comment by yhirose** [comment] 2018-06-17 03:13
Your cmake file looks probably OK. So there must be a different factor.

Could you do the following simple test for me?

In a terminal window:
```bash
git clone https://github.com/yhirose/cpp-httplib.git
cd cpp-httplib/example
g++ simplesvr.cc -I.. -lpthread
./a.out
```

In another terminal window:
```bash
curl http://localhost:8080/simplesvr.cc
```

In my case, `curl` successfully dumps the content of `simplesvr.cc` in the terminal window. How about your case?

**Comment by how0723** [comment] 2018-06-17 03:20
in my case 
I opened a terminal and type
curl http://localhost:8082/index.html
it successfully dumps the content of index.html .

but on the another pc
I can not visit the index.html

**Comment by yhirose** [comment] 2018-06-17 03:31
In order to access the HTTP server from another machine, you have to set the correct hostname or IP address of the machine on which the HTTP server running.

```bash
curl http://[hostname of IP address of the machine on which the HTTP server running]:8082/index.html
```

Is that the reason why you cannot access to the server from another machine?

**Comment by how0723** [comment] 2018-06-17 03:33
I have set the correnct IP address of the server machine
curl http://192.168.0.134:8082/index.html

**Comment by how0723** [comment] 2018-06-17 03:38
curl: (7) Failed to connect to 192.168.0.134 port 8082: 拒绝连接
拒绝连接 = connection denied
why

**Comment by how0723** [comment] 2018-06-17 03:41
is the reason of firewall ?

**Comment by yhirose** [comment] 2018-06-17 10:52
You may check with running the following simple server to see if it's a firewall issue.

```bash
python -m SimpleHTTPServer 8082 # python 2.x
```
or
```bash
python3 -m http.server 8082 # python 3.x
```

**Comment by how0723** [comment] 2018-06-17 11:02
okay 
I used python to test it , it works well , so it not the reason of firewall
now I can visit the http-server on local mathine , but on the anther mathine , I can visit , it replay me that connection refulsed
I have closed the firewall or open the port of 80

**Comment by how0723** [comment] 2018-06-17 11:18
I have found the reason 
we can not write code like this , if we write like this , we can only visit the http-server on the local machine.
svr.listen("localhost", port); //localhost

if we write like this , we can visit the http-server on anther machine
svr.listen("0.0.0.0", port);

**Comment by yhirose** [comment] 2018-06-17 11:40
Glad to hear that! I'll close this issue.

**Closed by yhirose** 2018-06-17 11:40 UTC

**Comment by how0723** [comment] 2018-06-18 02:16
you must change your code to save developers time
