### ISSUE TITLE
Error when running simple example client with SSL and MinGW on Windows

### ISSUE THREAD

**Issue by dalum** [yhirose/cpp-httplib#722] opened 2020-10-26 17:24 UTC
Hi!

Using the `ca-bundle.crt` in `/example` and compiling the following with with MinGW64 on Windows
```cpp
// client.cc

#include <httplib.h>
#include <iostream>

#define CA_CERT_FILE "./ca-bundle.crt"

using namespace std;

int main(void) {
  httplib::SSLClient cli("google.com", 443);
  cli.set_ca_cert_path(CA_CERT_FILE);
  cli.enable_server_certificate_verification(true);

  if (auto res = cli.Get("/hi")) {
    cout << res->status << endl;
    cout << res->get_header_value("Content-Type") << endl;
    cout << res->body << endl;
  } else {
    cout << "error code: " << res.error() << std::endl;
    auto result = cli.get_openssl_verify_result();
    if (result) {
      cout << "verify error: " << X509_verify_cert_error_string(result) << endl;
    }
  }

  return 0;
}
```
using:
```
g++ -o client -std=gnu++11 -I.. -Wall -Wextra -pthread client.cc -DCPPHTTPLIB_OPENSSL_SUPPORT -I/mingw64/include -L/mingw64/lib -lws2_32 -lcrypt32 -lcryptui -lssl -lcrypto -DCPPHTTPLIB_ZLIB_SUPPORT -lz
```
it compiles and links fine, but when running the compiled program, I get:
```
> ./client.exe
error code: 2
```
If the libraries `-lws2_32 -lcrypt32 -lcryptui` are omitted, the error code becomes `8` instead.  This only happens on Windows with GCC, and compiles fine on Linux.

Any suggestions or help would be much appreciated! :relaxed:

**Comment by yhirose** [comment] 2020-10-26 22:12
@dalum, thanks for the feedback. I am not using MinGW. So I don't have any clue about the error...

**Comment by PixlRainbow** [comment] 2020-10-27 01:29
Error code 2 is connection problem/couldn't establish a connection. Not sure why it only happens on Windows.

**Comment by yhirose** [comment] 2020-10-28 00:40
@dalum, error 2 and 8 mean that `Connection` and `SSLConnection` errors.
https://github.com/yhirose/cpp-httplib#error-code

It may not be an issue by MingGW, but your network or SSL configuration. Anyway, I think it's not a problem caused by cpp-httplib. So, I'll close it. But if you find any evidence that cpp-httplib causes it, please let me know.

Hope you find the real cause of it!

**Closed by yhirose** 2020-10-28 00:40 UTC

**Comment by bmmogensen** [comment] 2020-10-31 08:48
I am able to reproduce the errors described by @dalum both with and without -lws2_32 -lcrypt32 -lcryptui,

In order to shed some light as to what is going wrong, I've added the following lines of code to httplib.h:6065 near SSL_connect:
`        int ssl_error = 0;
        if ((ssl_error = SSL_connect(ssl)) != 1) {
          ssl_error = SSL_get_error(ssl, ssl_error);
          char err[1024];
          ERR_error_string(ssl_error, err);
          std::cout << "ssl_error: " << ssl_error << " - " << err << std::endl;
          error_ = Error::SSLConnection;
          return false;
        }`

I build the code using:
`g++ -o client -std=gnu++11 -I.. -Wall -Wextra -pthread client.cc -DCPPHTTPLIB_OPENSSL_SUPPORT -I/mingw64/include -L/mingw64/lib -lssl -lcrypto -DCPPHTTPLIB_ZLIB_SUPPORT -lz
`
and get the following error:
`
$ ./client.exe
ssl_error: 5 - error:00000005:lib(0):func(0):DH lib
error code: 8
`
Looking at the SSL documentation on this error does not help much, but it seems to be early on in the handshake, so perhaps the problem lies be elsewhere. 

The code works on Windows using the MSVC compiler or on Linux using the GCC compiler. 

Not sure how to debug this problem further. Do you have any ideas?

**Comment by PixlRainbow** [comment] 2020-10-31 17:03
ERR_error_string should not be used directly with SSL_get_error. ERR_error_string is intended to be used with a **DIFFERENT** set of error codes, from ERR_get_error, and will print the wrong error string if used with the output of SSL_get_error.  
SSL_get_error() is meant to be used with a user-written switch statement, possible values seen [here](https://www.openssl.org/docs/man1.1.1/man3/SSL_get_error.html#RETURN-VALUES).  
  
If, however, the return value of SSL_get_error is **`SSL_ERROR_SYSCALL`** or **`SSL_ERROR_SSL`** then you will need to call ERR_get_error() and **THEN** put it through ERR_get_error.

**Comment by bmmogensen** [comment] 2020-11-01 10:15
Thanks for the pointers regarding ERR_get_error() PixlRainbow. I changed the code to:
```
        int ssl_error = 0;
        if ((ssl_error = SSL_connect(ssl)) != 1) {
          ssl_error = SSL_get_error(ssl, ssl_error);
          std::cout << "ssl_error: " << ssl_error;
          if (ssl_error == SSL_ERROR_SYSCALL || ssl_error == SSL_ERROR_SSL) {
            char err[1024];
            auto sys_error = ERR_get_error();
            ERR_error_string(sys_error, err);
            std::cout << " - " << sys_error << " - " << err << std::endl;
          } else std::cout << std::endl;
          error_ = Error::SSLConnection;
          return false;
        }
```
It now gives:
```
ssl_error: 5 - 0 - error:00000000:lib(0):func(0):reason(0)
error code: 8
```
That seems less helpful though. But perhaps it's an indication that there's something with the socket library. I tried a simple s/_WIN32/_MSC_VER to remove any win32-specific setting, but that did not help. Then I tried setting -D_WIN32, which actually does not compile. So that's at least a hint at what needs to get fixed. I'm getting the following compile errors with -D_WIN32:
```
In file included from client.cc:3:
/usr/include/httplib.h: In lambda function:
/usr/include/httplib.h:1624:71: error: cannot convert ‘timeval*’ to ‘PTIMEVAL’ {aka ‘__ms_timeval*’}
 1624 |     return select(static_cast<int>(sock + 1), &fds, nullptr, nullptr, &tv);
      |                                                                       ^~~
      |                                                                       |
      |                                                                       timeval*
In file included from /usr/include/httplib.h:128,
                 from client.cc:3:
/usr/include/w32api/winsock2.h:1025:116: note:   initializing argument 5 of ‘int select(int, fd_set*, fd_set*, fd_set*, PTIMEVAL)’
 1025 |   WINSOCK_API_LINKAGE int WSAAPI select(int nfds,fd_set *readfds,fd_set *writefds,fd_set *exceptfds,const PTIMEVAL timeout);
      |                                                                                                     ~~~~~~~~~~~~~~~^~~~~~~
In file included from client.cc:3:
/usr/include/httplib.h: In lambda function:
/usr/include/httplib.h:1648:71: error: cannot convert ‘timeval*’ to ‘PTIMEVAL’ {aka ‘__ms_timeval*’}
 1648 |     return select(static_cast<int>(sock + 1), nullptr, &fds, nullptr, &tv);
      |                                                                       ^~~
      |                                                                       |
      |                                                                       timeval*
In file included from /usr/include/httplib.h:128,
                 from client.cc:3:
/usr/include/w32api/winsock2.h:1025:116: note:   initializing argument 5 of ‘int select(int, fd_set*, fd_set*, fd_set*, PTIMEVAL)’
 1025 |   WINSOCK_API_LINKAGE int WSAAPI select(int nfds,fd_set *readfds,fd_set *writefds,fd_set *exceptfds,const PTIMEVAL timeout);
      |                                                                                                     ~~~~~~~~~~~~~~~^~~~~~~
In file included from client.cc:3:
/usr/include/httplib.h: In lambda function:
/usr/include/httplib.h:1684:68: error: cannot convert ‘timeval*’ to ‘PTIMEVAL’ {aka ‘__ms_timeval*’}
 1684 |     return select(static_cast<int>(sock + 1), &fdsr, &fdsw, &fdse, &tv);
      |                                                                    ^~~
      |                                                                    |
      |                                                                    timeval*
In file included from /usr/include/httplib.h:128,
                 from client.cc:3:
/usr/include/w32api/winsock2.h:1025:116: note:   initializing argument 5 of ‘int select(int, fd_set*, fd_set*, fd_set*, PTIMEVAL)’
 1025 |   WINSOCK_API_LINKAGE int WSAAPI select(int nfds,fd_set *readfds,fd_set *writefds,fd_set *exceptfds,const PTIMEVAL timeout);
      |                                                                                                     ~~~~~~~~~~~~~~~^~~~~~~
In file included from client.cc:3:
/usr/include/httplib.h: In function ‘void httplib::detail::set_nonblocking(socket_t, bool)’:
/usr/include/httplib.h:1913:30: error: cannot convert ‘long unsigned int*’ to ‘__ms_u_long*’ {aka ‘unsigned int*’}
 1913 |   ioctlsocket(sock, FIONBIO, &flags);
      |                              ^~~~~~
      |                              |
      |                              long unsigned int*
In file included from /usr/include/httplib.h:128,
                 from client.cc:3:
/usr/include/w32api/winsock2.h:1007:76: note:   initializing argument 3 of ‘int ioctlsocket(SOCKET, int, __ms_u_long*)’
 1007 |   WINSOCK_API_LINKAGE int WSAAPI ioctlsocket(SOCKET s,__LONG32 cmd,u_long *argp);
      |                                                                            ^
In file included from client.cc:3:
/usr/include/httplib.h: In function ‘bool httplib::detail::is_chunked_transfer_encoding(const Headers&)’:
/usr/include/httplib.h:2610:11: error: ‘_stricmp’ was not declared in this scope; did you mean ‘strncmp’?
 2610 |   return !strcasecmp(get_header_value(headers, "Transfer-Encoding", 0, ""),
      |           ^~~~~~~~~~
In file included from client.cc:3:
/usr/include/httplib.h: In instantiation of ‘ssize_t httplib::detail::handle_EINTR(T) [with T = httplib::detail::select_read(socket_t, time_t, time_t)::<lambda()>; ssize_t = long int]’:
/usr/include/httplib.h:1625:4:   required from here
/usr/include/httplib.h:1598:13: error: void value not ignored as it ought to be
 1598 |     res = fn();
      |           ~~^~
/usr/include/httplib.h: In instantiation of ‘ssize_t httplib::detail::handle_EINTR(T) [with T = httplib::detail::select_write(socket_t, time_t, time_t)::<lambda()>; ssize_t = long int]’:
/usr/include/httplib.h:1649:4:   required from here
/usr/include/httplib.h:1598:13: error: void value not ignored as it ought to be
/usr/include/httplib.h: In instantiation of ‘ssize_t httplib::detail::handle_EINTR(T) [with T = httplib::detail::wait_until_socket_is_ready(socket_t, time_t, time_t)::<lambda()>; ssize_t = long int]’:
/usr/include/httplib.h:1685:4:   required from here
/usr/include/httplib.h:1598:13: error: void value not ignored as it ought to be
```

**Comment by bmmogensen** [comment] 2020-11-02 11:22
I managed to get it working by using the following command line:
```
g++ -o client -std=gnu++11 -I.. -Wall -Wextra -pthread client.cc -DCPPHTTPLIB_OPENSSL_SUPPORT -I/mingw64/include -L/mingw64/lib -lssl -lcrypto -DCPPHTTPLIB_ZLIB_SUPPORT -lz -D_WIN32 -DCPPHTTPLIB_USE_POLL -Dstrcasecmp=strcasecmp -lws2_32  -lcrypt32
```
Perhaps it can be done more elegantly to support also the case when CPPHTTPLIB_USE_POLL is not defined.
