### ISSUE TITLE
Requests from browsers seem to freeze server on Windows

### ISSUE THREAD

**Issue by xy4455** [yhirose/cpp-httplib#454] opened 2020-04-30 07:05 UTC
I'm seeing a 5-10 second freeze in the handling of requests for the example test server whenever I make a request from a browser with the server running on a windows machine.

This is my set-up:

I'm running the example server on a windows machine. I've got a couple of scripts calling the `/dump` endpoint as fast as they can using `curl`. This is fine and I can have multiple clients calling dump without any issues (response times in the order of milliseconds).

However, as soon as I make one request from a browser all other clients freeze for 5-10 seconds before continuing. The response to the browser is also fairly slow.

This is the dump from the request from the browser that is causing the issue:
```
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,nl;q=0.8
Connection: keep-alive
Host: 127.0.0.1:8080
REMOTE_ADDR: 127.0.0.1
REMOTE_PORT: 59759
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36
```

**Comment by PixlRainbow** [comment] 2020-04-30 08:35
web browsers use significantly more system resources than simple clients like curl. Have you checked to see if the web browser is not simply competing with the server for CPU time or memory?
If not, then I suspect the browser is waiting for some sort of negotiation to occur, or that the server is trying to keep-alive the connection but not flushing the response correctly until a timeout occurs.

**Comment by xy4455** [comment] 2020-04-30 08:46
Thanks for your reply.

> Have you checked to see if the web browser is not simply competing with the server for CPU time or memory?

To rule that out I've made the request from a different machine (my phone in fact).. but I'm observing the same behaviour unfortunately. 

When I'm doing the request I don't see significant activity in the task manager either.

**Comment by xy4455** [comment] 2020-04-30 08:47
>or that the server is trying to keep-alive the connection but not flushing the response correctly until a timeout occurs. 

My gut feel (without knowing much about http-lib or http in fact) is that it is something like that. The server seems to be waiting for something, and also there is this `Connection: keep-alive` in the request.

**Comment by xy4455** [comment] 2020-04-30 09:12
Perhaps unsurprising, but by changing some `#define`s I can alter the behaviour:

What I'm basically doing is disabling keep-alive and setting the maximum read time out to really low (50 us). When configured like that I can't reproduce the problem.

So I think this confirms your idea about the negotiation going on. 

Please let me know if I can do anything else to assist. 

```
#ifndef CPPHTTPLIB_KEEPALIVE_TIMEOUT_SECOND
#define CPPHTTPLIB_KEEPALIVE_TIMEOUT_SECOND 0
#endif

#ifndef CPPHTTPLIB_KEEPALIVE_TIMEOUT_USECOND
#define CPPHTTPLIB_KEEPALIVE_TIMEOUT_USECOND 0
#endif

#ifndef CPPHTTPLIB_KEEPALIVE_MAX_COUNT
#define CPPHTTPLIB_KEEPALIVE_MAX_COUNT 0
#endif

#ifndef CPPHTTPLIB_READ_TIMEOUT_SECOND
#define CPPHTTPLIB_READ_TIMEOUT_SECOND 0
#endif

#ifndef CPPHTTPLIB_READ_TIMEOUT_USECOND
#define CPPHTTPLIB_READ_TIMEOUT_USECOND 50

**Comment by yhirose** [comment] 2020-04-30 11:16
@xy4455, thanks for the feedback. Is your request from browser "GET" or "POST"? If your request is a POST request, does it have "Content-Length" header? (If possible, could you give me your complete client request dump as well?)

This looks the  common symptom when a client sends a request without "Content-Length" and the server waits unknown length of body content until the read timeout occurs.

**Comment by xy4455** [comment] 2020-04-30 11:43
I think it should be a GET request, I'm just literally typing in the chrome's address bar: `http://localhost:8080/dump`.

> (If possible, could you give me your complete client request dump as well?)

```
  svr.Get("/dump", [](const Request &req, Response &res) {
    res.set_content(dump_headers(req.headers), "text/plain");
  });
```
I used this snippet to generate the dump at the top of this thread, I'd be happy to give you more info, but I'm not sure what exactly?

**Comment by yhirose** [comment] 2020-04-30 16:44
@xy4455, thanks for the information. I tried it on my machine,  but the GET request took 4 ms with the default `#define` configurations. I don't know why I can't reproduce it with the way that you do...

<img width="1224" alt="Screen Shot 2020-04-30 at 12 35 25 PM" src="https://user-images.githubusercontent.com/357397/80736324-f7536800-8adf-11ea-806c-95b6ad7a73a7.png">
<img width="978" alt="Screen Shot 2020-04-30 at 12 43 16 PM" src="https://user-images.githubusercontent.com/357397/80736478-3386c880-8ae0-11ea-85d9-309c38c42a56.png">

Do you know which `#define` configuration actually fixes the problem on your machine?
Thank you for your investigation!

**Comment by xy4455** [comment] 2020-04-30 18:18
Thanks for looking into this. 

I've been trying to get a clearer reproduction scenario, and it seems this only occurs when I have multiple clients.

So I have one shell script (source below) making requests. It is always fast (win or Mac) but when I do a browser request in parallel I see sometimes requests taking as much as 12 seconds. 

I didn't have time for an exhaustive search, but found that changing to the values below helped (n=1, sorry about that).



```
#ifndef CPPHTTPLIB_KEEPALIVE_TIMEOUT_SECOND
#define CPPHTTPLIB_KEEPALIVE_TIMEOUT_SECOND 0
#endif

#ifndef CPPHTTPLIB_KEEPALIVE_TIMEOUT_USECOND
#define CPPHTTPLIB_KEEPALIVE_TIMEOUT_USECOND 50

```



Script
```
#!/bin/bash
TIMEFORMAT='%3R'	
for i in {1..50000}
do
   #time curl 192.168.2.161:12345/version -I -o headers -s
   time curl 192.168.2.161:8080/hi -I -o headers -s

   #cat headers | head -n 1 | cut '-d ' '-f2' 
done
```

**Comment by yhirose** [comment] 2020-04-30 23:28
@xy4455, thank you for the additional information. I tried what you mentioned on my Mac, but the browser received requests immediately. (I run two shell scripts, and manually sent requests from Chrome browser.)

I don't understand why the difference happens... But at least, your investigation shows that the current implementation for the keep alive timeout may have something wrong. This configuration is used here:

https://github.com/yhirose/cpp-httplib/blob/8333340e2cdf370d9c6ac4020e5fcaa1b2ece1da/httplib.h#L1351-L1356

https://github.com/yhirose/cpp-httplib/blob/8333340e2cdf370d9c6ac4020e5fcaa1b2ece1da/httplib.h#L4590-L4596

I'll keep investing the connection timeout issue. I also wonder if I should disable the keep-alive timeout configuration for now until this problem is fixed. because it seems like this issue causes the really bad performance problem to a number of users. (Or suggests users to set `CPPHTTPLIB_KEEPALIVE_MAX_COUNT` to 0 if the performance problem happens.)

Anyway, thank you so much about your investigation. I'll get back to you when I find something. Of course, any additional information is welcome. Thank you!

**Comment by huangshangbin** [comment] 2020-05-01 03:44
> I'll keep investing the connection timeout issue. I also wonder if I should disable the keep-alive timeout configuration for now until this problem is fixed. because it seems like this issue causes the really bad performance problem to a number of users. (Or suggests users to set `CPPHTTPLIB_KEEPALIVE_MAX_COUNT` to 0 if the performance problem happens.)
> 
> Anyway, thank you so much about your investigation. I'll get back to you when I find something. Of course, any additional information is welcome. Thank you!



You're right., the service is not started, the client sends the request unfriendly, and #define CPPHTTPLIB_READ_TIMEOUT_SECOND 50. There is also a problem with the time. When I upload the file, it often times out. I changed it to 500

**Comment by xy4455** [comment] 2020-05-01 11:51
Hi, thanks for looking into it. By disabling the keep-alive feature the problem becomes a lot smaller my simple test environment. But unfortunately it doesn't seem to solve the performance problems as soon as I connect my http server to our javascript front-end. That front-end will generate up to 10 requests per second in parallel (still a small number) but that does seem to choke the connection again.

I'm disabling the keep alive using this:
```
    auto svr = Server();
    svr.set_keep_alive_max_count(0);
```

I'm not sure if it is important, but we are running the server in a windows vm.

**Comment by yhirose** [comment] 2020-05-01 12:20
@xy4455, it's interesting... If you set `CPPHTTPLIB_KEEPALIVE_MAX_COUNT` to 0, both `CPPHTTPLIB_KEEPALIVE_TIMEOUT_SECOND` and CPPHTTPLIB_KEEPALIVE_TIMEOUT_USECOND` won't be used at all. So if the performance problem still happens, it should be caused by something else.

Could you try to set `CPPHTTPLIB_THREAD_POOL_COUNT` to 20 and see what will happen?
Thank you for your help!

**Comment by PixlRainbow** [comment] 2020-05-01 13:32
> I'm not sure if it is important, but we are running the server in a windows vm  

by default, httplib will use the same number of threads as the number of cores available. If your VM only exposes 1 core, then httplib will run single-threaded. However, you can force the use of more threads by defining `CPPHTTPLIB_THREAD_POOL_COUNT` as yhirose has said.

**Comment by xy4455** [comment] 2020-05-01 13:51
>Could you try to set CPPHTTPLIB_THREAD_POOL_COUNT to 20 and see what will happen?
Thank you for your help!

Yes, thanks that does seem to resolve my issue!

**Comment by yhirose** [comment] 2020-05-01 14:09
@PixlRainbow, thanks for the clear explanation.

@xy4455, glad to hear the news. Could you try the following code on your Windows VM?

```cpp
#define CPPHTTPLIB_THREAD_POOL_COUNT                                           \
  ((std::max)(5u, std::thread::hardware_concurrency() - 1))
```

The above change guarantees that at least 5 threads are assigned to the thread pool as default even if `std::thread::hardware_concurrency()` returns a small number like one or two.

I think the change is reasonable even for machines with few cores, and can make most users happy.

**Comment by xy4455** [comment] 2020-05-01 14:23
@yhirose The change you suggest works well for me.

Thanks again for all the help.

I would perhaps as a user like to set this number of threads per server instance, there is currently no way of doing that right?

Also, I was thinking, would it be possible to read the socket for the keep-alive connections without blocking the main server thread? That seems to me the root cause of the issue here. But again, I'm don't know the codebase, so I might be asking for something impossible here.

Anyway, thanks again. Httplib has been a joy to work with so far.

**Comment by yhirose** [comment] 2020-05-02 01:25
@xy4455, I have changed the default value of `CPPHTTPLIB_THREAD_POOL_COUNT` back to 8. I guess this number is reasonable even if a single core or dual core machines.

> I would perhaps as a user like to set this number of threads per server instance, there is currently no way of doing that right?

There is a way to do it.

```cpp
Server svr;
svr.new_task_queue = [] { return new ThreadPool(20); };
```

I didn't intentionally add a method like `set_thread_count` to the `Server` class because `ThreadPool` class is just a default implementation of `TaskQueue`, and the method may not fit in  other implementations of `TaskQueue`.

> I was thinking, would it be possible to read the socket for the keep-alive connections without blocking the main server thread? ? That seems to me the root cause of the issue here.

I am not sure why the problem occurs when a single thread, yet. When I have time, I'll look into it.

Thank you for your help!

**Closed** 2020-05-02 01:25 UTC
Labels: bug

**Comment by oren-nonamesecurity** [comment] 2020-09-14 14:42
Hi, I came across a similar issue on multiple linux machines.
GET requests hang for 5 seconds when multiple clients are in place.
Setting `CPPHTTPLIB_KEEPALIVE_MAX_COUNT` or `CPPHTTPLIB_KEEPALIVE_TIMEOUT_SECOND` to 0 solves the delay but is probably impacting performance without keeping the connection open.

Any other solution for this? This sounds like a real bug.

**Comment by yhirose** [comment] 2020-09-26 01:23
@oren-nonamesecurity, does the problem on your machines still happen even with the latest httplib.h? If so, could you give me the actual value of `CPPHTTPLIB_THREAD_POOL_COUNT` on your Linux machine? (It should be at least 8.) Those answers could help me to see if it's the thread count problem or the keep-alive implementation problem. Also if you give me the smallest possible code that can reproduce the problem on both server and client sizes, it will be very much helpful to looking the problem. Thanks!
