### ISSUE TITLE
Performance degrades when keep-alive is used

### ISSUE THREAD

**Issue by yesvivek** [yhirose/cpp-httplib#707] opened 2020-10-19 21:21 UTC
When running simple hello-world server with this library, I see vast difference in performance with versus without keep-alive option of apache benchmark tool (keep-alive gives much slower performance). No overrides of any config, 8 threads were created automatically by httplib.h (used latest on github at the time of reporting this).

Am assuming this is unexpected. Is there any reason why this happens with httplib.h?

I tried similar tests with apache (mpm_worker) and found keep-alive is 4x faster than non-keep-alive tests as expected (on same machine and compiler).

```
void hello_handler(const httplib::Request& req, httplib::Response& res) {
        res.set_content("Hello World!", "text/plain");
}

int main() {
        const int serverPort = 80;
        const char* serverHost = "127.0.0.1";
        httplib::Server server;

        server.Get("/hello", hello_handler);

        server.Get("/stop", [&](const httplib::Request& req, httplib::Response& res){
                server.stop();
        });

        std::cout << "Listening on " << serverHost << ":" << serverPort << "\n";

        if(!server.listen(serverHost, serverPort)) {
                std::cerr << "Error listening on port " << serverPort << "\n";
                return 2;
        }

        std::cout << "Exiting..\n";
        return 0;
}
```
ab results, both one after the other one,
```
ab -c 8 -n 400 'http://127.0.0.1/hello'
This is ApacheBench, Version 2.3 <$Revision: 1843412 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Finished 400 requests


Server Software:
Server Hostname:        127.0.0.1
Server Port:            80

Document Path:          /hello
Document Length:        12 bytes

Concurrency Level:      8
Time taken for tests:   0.233 seconds
Complete requests:      400
Failed requests:        0
Total transferred:      42800 bytes
HTML transferred:       4800 bytes
Requests per second:    1715.64 [#/sec] (mean)
Time per request:       4.663 [ms] (mean)
Time per request:       0.583 [ms] (mean, across all concurrent requests)
Transfer rate:          179.27 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    1   0.7      1       4
Processing:     1    3   1.9      3      19
Waiting:        0    2   1.9      2      19
Total:          1    5   1.9      4      19

Percentage of the requests served within a certain time (ms)
  50%      4
  66%      5
  75%      5
  80%      5
  90%      6
  95%      8
  98%      9
  99%     11
 100%     19 (longest request)
```

```
ab -k -c 8 -n 400 'http://127.0.0.1/hello'
This is ApacheBench, Version 2.3 <$Revision: 1843412 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Finished 400 requests


Server Software:
Server Hostname:        127.0.0.1
Server Port:            80

Document Path:          /hello
Document Length:        12 bytes

Concurrency Level:      8
Time taken for tests:   1.391 seconds
Complete requests:      400
Failed requests:        0
Keep-Alive requests:    324
Total transferred:      41964 bytes
HTML transferred:       4800 bytes
Requests per second:    287.50 [#/sec] (mean)
Time per request:       27.827 [ms] (mean)
Time per request:       3.478 [ms] (mean, across all concurrent requests)
Transfer rate:          29.45 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.2      0       1
Processing:     0   27  21.3     43      49
Waiting:        0    1   0.6      1       5
Total:          0   27  21.2     43      49

Percentage of the requests served within a certain time (ms)
  50%     43
  66%     44
  75%     44
  80%     44
  90%     45
  95%     48
  98%     48
  99%     48
 100%     49 (longest request)
```

### Environment details:
gcc version 8.3.0
Compiled using: g++ httpserver.cpp -pthread
x86_64-linux-gnu

**Comment by yhirose** [comment] 2020-10-20 00:10
@yesvivek, thanks for the detailed report! I'll investigate it when I have time.

**Comment by yhirose** [comment] 2020-10-20 03:33
@yesvivek, I acknowledged the problem.

```
> ab -c 8 -n 400 'http://127.0.0.1:8080/hello'
This is ApacheBench, Version 2.3 <$Revision: 1843412 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Finished 400 requests


Server Software:        
Server Hostname:        127.0.0.1
Server Port:            8080

Document Path:          /hello
Document Length:        12 bytes

Concurrency Level:      8
Time taken for tests:   0.063 seconds
Complete requests:      400
Failed requests:        0
Total transferred:      42800 bytes
HTML transferred:       4800 bytes
Requests per second:    6358.39 [#/sec] (mean)
Time per request:       1.258 [ms] (mean)
Time per request:       0.157 [ms] (mean, across all concurrent requests)
Transfer rate:          664.40 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.1      0       1
Processing:     1    1   0.2      1       2
Waiting:        0    1   0.2      1       2
Total:          1    1   0.2      1       2

Percentage of the requests served within a certain time (ms)
  50%      1
  66%      1
  75%      1
  80%      1
  90%      1
  95%      2
  98%      2
  99%      2
 100%      2 (longest request)

> ab -k -c 8 -n 400 'http://127.0.0.1:8080/hello'
This is ApacheBench, Version 2.3 <$Revision: 1843412 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Finished 400 requests


Server Software:        
Server Hostname:        127.0.0.1
Server Port:            8080

Document Path:          /hello
Document Length:        12 bytes

Concurrency Level:      8
Time taken for tests:   0.073 seconds
Complete requests:      400
Failed requests:        0
Keep-Alive requests:    323
Total transferred:      41953 bytes
HTML transferred:       4800 bytes
Requests per second:    5489.45 [#/sec] (mean)
Time per request:       1.457 [ms] (mean)
Time per request:       0.182 [ms] (mean, across all concurrent requests)
Transfer rate:          562.25 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.1      0       1
Processing:     1    1   0.3      1       3
Waiting:        1    1   0.3      1       3
Total:          1    1   0.3      1       3

Percentage of the requests served within a certain time (ms)
  50%      1
  66%      2
  75%      2
  80%      2
  90%      2
  95%      2
  98%      2
  99%      2
 100%      3 (longest request)
```

**Comment by yhirose** [comment] 2020-12-01 19:25
@yesvivek, I just get back to this issue, and I first tried benchmarking with the builtin Apache on my macOS.

```
 ~$ sudo apachectl start

 ~$ curl http://localhost/
<html><body><h1>It works!</h1></body></html>

 ~$ ab -c 8 -n 400 http://localhost/
This is ApacheBench, Version 2.3 <$Revision: 1843412 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Finished 400 requests


Server Software:        Apache/2.4.41
Server Hostname:        localhost
Server Port:            80

Document Path:          /
Document Length:        45 bytes

Concurrency Level:      8
Time taken for tests:   0.312 seconds
Complete requests:      400
Failed requests:        0
Total transferred:      140800 bytes
HTML transferred:       18000 bytes
Requests per second:    1281.46 [#/sec] (mean)
Time per request:       6.243 [ms] (mean)
Time per request:       0.780 [ms] (mean, across all concurrent requests)
Transfer rate:          440.50 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.0      0       0
Processing:     0    6   4.6      4      21
Waiting:        0    6   4.5      4      21
Total:          1    6   4.6      4      21

Percentage of the requests served within a certain time (ms)
  50%      4
  66%      8
  75%      9
  80%     10
  90%     13
  95%     15
  98%     18
  99%     20
 100%     21 (longest request)

 ~$ ab -k -c 8 -n 400 http://localhost/
This is ApacheBench, Version 2.3 <$Revision: 1843412 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Finished 400 requests


Server Software:        Apache/2.4.41
Server Hostname:        localhost
Server Port:            80

Document Path:          /
Document Length:        45 bytes

Concurrency Level:      8
Time taken for tests:   2.239 seconds
Complete requests:      400
Failed requests:        0
Keep-Alive requests:    397
Total transferred:      155076 bytes
HTML transferred:       18000 bytes
Requests per second:    178.65 [#/sec] (mean)
Time per request:       44.781 [ms] (mean)
Time per request:       5.598 [ms] (mean, across all concurrent requests)
Transfer rate:          67.64 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.0      0       0
Processing:     0   29 233.7      0    2225
Waiting:        0   28 233.7      0    2225
Total:          0   29 233.7      0    2225

Percentage of the requests served within a certain time (ms)
  50%      0
  66%      0
  75%      0
  80%      0
  90%      0
  95%      0
  98%     52
  99%   2187
 100%   2225 (longest request)
```

As you can see the above, the keep-alive is 10 times slower than the non-keep-alive even on Apache...

> I tried similar tests with apache (mpm_worker) and found keep-alive is 4x faster than non-keep-alive tests as expected (on same machine and compiler).

Could you give me more information about how you tested and got the result? Thanks for your help!

**Comment by yhirose** [comment] 2020-12-06 13:19
@yesvivek, any response?

**Comment by yesvivek** [comment] 2020-12-09 13:49
@yhirose , sorry I missed notifications as am not using cpp-httplib anymore. Also, I have destroyed the VM which had apache and cpp-httplib, so cannot redo the tests now.
I compared performance with apache httpd only to showcase there is no problem with environmental where cpp-httplib is run (if I have had problems with env, I would seen httpd's keepalive performance to be low too).
All I did was use Apache httpd with mpm_worker that is not even tuned for performance or anything, so not sure why you see such results. Running the tests multiple times showed similar results?

**Comment by yhirose** [comment] 2020-12-09 15:33
@yesvivek, yes, I get the similar result every time I tested on the builtin Apache server on Mac. According to the keep-alive code in httplib.h, I don't find any place where I can make performance improvement for Keep-Alive connection, because it's pretty strait-forward simple loop logic with almost no overhead. So I have no clue to improve the performance at this point... Anyway, I'll keep looking on it. Thanks!

**Comment by yesvivek** [comment] 2020-12-10 08:57
@yhirose , trying suggestions from [this answer](https://stackoverflow.com/questions/42426206/httpserver-very-slow-with-keepalive) help?

**Comment by yhirose** [comment] 2020-12-19 17:26
@yesvivek, I'll take a look at the post when I have time. Thanks!

**Comment by yhirose** [comment] 2020-12-19 23:07
@yesvivek, I tried with `svr.set_tcp_nodelay(true)` in `example/hello.cc`, but it doesn't help and the keep-alive is still slow... But anyway, the keep-alive result on Apache is also slow which means cpp-httplib behaves in the same way as Apache on my machine...

**Comment by yhirose** [comment] 2020-12-25 18:40
I concluded that this could happen with any kind of HTTP server depending on a network environment. I'll close it for now because I have the same exact behavior in the Apache on my machine. When I get more proof that could help me to reproduce this problem, I'll work on that.

**Closed by yhirose** 2020-12-25 18:40 UTC
Labels: need more information to verify
