### ISSUE TITLE
Segfault when stopping immediately after start

### ISSUE THREAD

**Issue by micjo** [yhirose/cpp-httplib#795] opened 2020-12-15 16:23 UTC
First of all, I would like to really thank you for this library. It's working great and its very lightweight to use compared to other open source projects out there. The problem i have is a niche one, i'll admit. Regardless if it would be my project i would want to know. You can obviously still decide if this is worth investigating.

When calling stop right after start, the httplib segfaults. This is the stacktrace i am getting :
![image](https://user-images.githubusercontent.com/5049483/102241446-41674d80-3ef9-11eb-9181-049cf435173d.png)

It is more likely to happen the more Gets you 'queue'. The code i have in my implementation:
![image](https://user-images.githubusercontent.com/5049483/102241736-93a86e80-3ef9-11eb-87d1-e7054f8aa7bc.png)

this sleep_for fixes my segfault. This is not happening 100%, but more than 75%. (Tried > 20 times)

**Comment by yhirose** [comment] 2020-12-15 18:10
@micjo, thank you for the feedback.  Could you try with the following code right after the thread is created?

```cpp
  }).detach();

  // Wait until the server is ready.
  while (!_svr.is_running()) {
    std::this_thread::sleep_for(std::chrono::milliseconds(10));
  }
```

**Comment by micjo** [comment] 2020-12-16 09:48
This does indeed solve my problem. Allthough i do still see some odd behavior:

Keeping the code as is and printing the svr is running state, i can clearly see that if its 0, it segfaults, if its 1 it does not. (sleeping a bit makes it 1)

However if i change my final Get to :
![image](https://user-images.githubusercontent.com/5049483/102332221-1843cd00-3f8c-11eb-8a0b-bcaed0eceb3f.png)

It will not segfault even when the running state is 0... . Im guessing there is some difference in construction time based on that regex or other items that are unknown to me. Regardless i will add this is_running() to my constructor.

**Comment by yhirose** [comment] 2020-12-16 12:52
@micjo, glad to hear the problem is solved. I'll close it. As for another regex issue that you found, could you provide a unit test  in `test/test.cc` or a smallest possible code to reproduce it in another separate issue because it has nothing to do with this issue? Thanks!

**Closed by yhirose** 2020-12-16 12:52 UTC
