### ISSUE TITLE
post using FormData

### ISSUE THREAD

**Issue by bigbao9494** [yhirose/cpp-httplib#1557] opened 2023-04-15 02:13 UTC
js:  send data to server,pic_index=1
var data = new FormData()
data.append('pic_index', 1)
axios.post("http://127.0.0.1/post",data)

cpp:  Both methods cannot parse the correct data (pic_index, 1)
svr.Post("/post", [](const Request &req, Response &res) {});
svr.Post("/post", [&](const Request &req, Response &res,const ContentReader &content_reader) {})

**Comment by yhirose** [comment] 2023-04-15 03:00
@bigbao9494 could you show the smallest possible complete JavaScript client code and complete C++ cpp-httplib server code, so that I can easily reproduce it? Thanks.

**Comment by bigbao9494** [comment] 2023-04-19 03:32
sorry it's too late

web code:

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>axios test</title>
    <script src="https://unpkg.com/axios@1.3.5/dist/axios.js"></script>
    <script>axios.defaults.baseURL = 'http://127.0.0.1:9090/'</script>
    <style>
        a {
            margin-left: 15px;
            margin-top: -10px;
        }
    </style>
</head>

<script>
function file_and_param() {
	let postData = new FormData()
	file1 = document.getElementsByName("f1")[0].files[0]
	console.log(file1)
	postData.append('file',file1)
	postData.append('pic_index',1)
					
	axios.post('/post',postData).then(response => {
		console.log("ok")
	}).catch(error => {
		console.log(error)
	})
}
function only_param1() {
	let postData = new FormData()
	postData.append('pic_index1',1)
	postData.append('pic_index2',2)
					
	axios.post('/post',postData).then(response => {
		console.log("ok")
	}).catch(error => {
		console.log(error)
	})
}
function only_param2() {
	let postData= new URLSearchParams()
	postData.append('pic_index1',1)
	postData.append('pic_index2',2)
					
	axios.post('/post',postData).then(response => {
		console.log("ok")
	}).catch(error => {
		console.log(error)
	})
}
</script>

<body>
	<div id="app">
		<input type="button" value="only_param1" onclick="only_param1();" />
		<input type="button" value="only_param2" onclick="only_param2();" />
		<div>
		<br>
		file_and_param
		<input name="f1" type="file" value="file_and_param" onchange="file_and_param();" />
		</div>
	</div>
</body>

</html>


cpp code:

#include <fstream>
#include <httplib.h>
#include <iostream>
using namespace httplib;
using namespace std;

const char *html = R"(
<form id="formElem">
  <input type="file" name="image_file" accept="image/*">
  <input type="file" name="text_file" accept="text/*">
  <input type="submit">
</form>
<script>
  formElem.onsubmit = async (e) => {
    e.preventDefault();
    let res = await fetch('/post', {
      method: 'POST',
      body: new FormData(formElem)
    });
    console.log(await res.text());
  };
</script>
)";

int upload_main(void) {
  Server svr;

  svr.Get("/", [](const Request & /*req*/, Response &res) {
    res.set_content(html, "text/html");
  });

#if 0 //first method
  svr.Options("/post", [&](const Request & /*req*/, Response &res) {
    res.set_header("Access-Control-Allow-Origin", "*");
  });

  svr.Post("/post", [](const Request &req, Response &res) {
      for (auto& mt : req.files)
      {
          cout << mt.first.c_str() << ":" << endl;
          cout << mt.second.name << "," << mt.second.filename << endl;
      }
    auto image_file = req.get_file_value("image_file");
    auto text_file = req.get_file_value("text_file");

    cout << "image file length: " << image_file.content.length() << endl
         << "image file name: " << image_file.filename << endl
         << "text file length: " << text_file.content.length() << endl
         << "text file name: " << text_file.filename << endl;

    {
      ofstream ofs(image_file.filename, ios::binary);
      ofs << image_file.content;
    }
    {
      ofstream ofs(text_file.filename);
      ofs << text_file.content;
    }

    res.set_content("done", "text/plain");
    res.set_header("Access-Control-Allow-Origin", "*");
  });
#else //second method

  svr.Options("/post",
      [&](const Request& /*req*/, Response& res) {
          res.set_header("Access-Control-Allow-Origin", "*");
      });

  svr.Post("/post", [&](const Request &req, Response &res,
                                    const ContentReader &content_reader) {
     res.set_header("Access-Control-Allow-Origin", "*");
    if (req.is_multipart_form_data())
    {
      // NOTE: `content_reader` is blocking until every form data field is read
      MultipartFormDataItems files;
      content_reader(
          [&](const MultipartFormData &file) {
            files.push_back(file);
            return true;
          },
          [&](const char *data, size_t data_length) {
            files.back().content.append(data, data_length);
            return true;
          });
    }
    else
    {
      std::string body;
      content_reader([&](const char *data, size_t data_length) {
        body.append(data, data_length);
        return true;
      });
    }
  });
#endif
  svr.listen("127.0.0.1", 9090);

  return 0;
}

**Comment by bigbao9494** [comment] 2023-04-20 03:44
@yhirose how about this question?

**Comment by yhirose** [comment] 2023-05-02 09:36
@bigbao9494 sorry that I was busy to look at your code. Could you make the code shorter, so that I can easily reproduce it? Thanks!

**Comment by bigbao9494** [comment] 2023-05-03 12:04
I will upload a zip file tomorrow,Easy for you to view。

**Comment by bigbao9494** [comment] 2023-05-04 10:50
[req_test.zip](https://github.com/yhirose/cpp-httplib/files/11396612/req_test.zip)
@yhirose it's zip file,upload.cc and html

**Comment by bigbao9494** [comment] 2023-05-13 02:40
@yhirose how about this question?

**Comment by bigbao9494** [comment] 2023-05-23 14:27
@yhirose how about this question?

**Comment by PixlRainbow** [comment] 2023-05-27 13:33
It appears you are using Axios.JS on your client side.
Based on the Axios documentation, it appears that Axios will send POST requests using the `application/x-www-form-urlencoded` content type by default. httplib `req.files` is only relevant for `multipart/form-data` POST requests.

**Comment by PixlRainbow** [comment] 2023-05-27 14:39
I have just tested the code you provided in the ZIP, and both methods work with no problems

**Comment by bigbao9494** [comment] 2023-05-30 01:32
@PixlRainbow @yhirose thanks a lot
Here are my test results using req_test.zip，I'm sure there's a problem:

Test results using interface  [](const Request&req, Response&res):
1. Click on only_param1 cannot get parameters from post anywhere
2. Click on only_param2 only parameters from Post can be geted in req.params
3. Click on file_and_param cannot get parameters from post anywhere

Test results using interface  [&](const Request &req, Response &res,const ContentReader &content_reader) :
1. Click on only_param1 cannot get parameters from post anywhere
2. Click on only_param2 cannot get parameters from post anywhere including req.params
3. Click on file_and_param cannot get parameters from post anywhere

**Comment by PixlRainbow** [comment] 2023-05-30 01:39
Which version of httplib are you using? Have you checked if you actually received any request on the server side and generated response?

**Comment by bigbao9494** [comment] 2023-05-30 09:08
Using the latest version, downloaded and tested it this morning. Confirm that the server has received data but has not parsed it.

**Comment by PixlRainbow** [comment] 2023-05-31 19:13
oh sorry, I did not notice that you had stored the problematic webpage in a separate file. I have just re-tested req_test.zip with the included HTML page.

## using interface `[](const Request&req, Response&res)`:
- I had to modify the code as the HTML file used different field names compared to the cpp embedded page.
- I had to add missing references to `mt.second.content` in the print statement of the for loop.

After I made these changes
1. Click on only_param1, both fields can be accessed through req,files
2. Click on only_param2, both fields can be accessed through req.params
3. Click on file_and_param, both fields can be accessed through req.files

## using interface `[&](const Request &req, Response &res,const ContentReader &content_reader)`:
- added a for loop in `if` block to print the fields collected in `files` local variable;
- added `Params params;` local variable in `else` block
- added call to `detail::parse_query_text` in `else` block to process the data collected in the local `body` variable and save the fields to `params` variable
- added a for loop in `else` block to print the fields collected in `params`

After I made these changes,
1. Click on only_param1, both fields can be accessed through `MultipartFormDataItems files;`
2. Click on only_param2, both fields can be accessed through `Params params;`
3. Click on file_and_param, , both fields can be accessed through `MultipartFormDataItems files;`

Note that when using ContentReader interface, all request body parsing is skipped and redirected to the ContentReader callback. This is because this interface is intended for users who want to handle the incoming request themselves in a streaming way that reduces memory usage.

**Comment by bigbao9494** [comment] 2023-06-01 06:08
@PixlRainbow thank a lot
After this modification, we can indeed obtain the data uploaded by the client, but there are still issues. I will explain in several parts, hoping to clarify:

1. Method used in HTML files:
    It is a common method for uploading files and parameters
    only_param1: Only upload parameters through FormData
    only_param2: Upload parameters through URLSearchParams
    file_and_param: Upload parameters and files through FormData, as sometimes additional information needs to be added to the uploaded file

2. The user of the interface only wants to obtain the data they want in a simple and clear manner when using it:
    If it could be as concise as Golang, it would be perfect. All parameters are in req.params (just read directly), and all files are in req.files.
    The modified upload.cc can indeed obtain data, but it is somewhat cumbersome to use.
    For example, the interface [&] (const Request&/* req */, Response&res) has parameters sometimes in req.params and sometimes in req.files. If they are all in req.files, the user cannot determine which ones are parameters.
    For example, the interface [&] (const Request&req, Response&res, const ContentReader&content-reader) sometimes has parameters in req.files, and sometimes requires calling parse_query_text needs to be parsed again, but the user is experiencing some crashes.

**Comment by PixlRainbow** [comment] 2023-06-01 06:31
For clarification about contentreader interface, it is designed to skip content parsing entirely. It is for users who want to handle request streaming themselves, but the side effect is that the user must also become responsible for parsing. Because body parsing is disabled, none of the fields of req will be populated except for headers.

**Comment by PixlRainbow** [comment] 2023-06-01 06:49
About the simple req res interface (without content reader): req.params are for requests formatted as "urlencoded" requests, while req.files are for "multipart" requests. 

Unfortunately, the HTTP protocol definition provides clients with multiple possible ways to encode multipart requests. It is valid for a client to attach files to a multipart form request without a filename (if the file is dynamically generated in memory by the client), and it is also valid to label file fields as form-data without distinguishing it from a text field. It is also valid to attach files in form fields without a content-type header. Therefore, it is extremely difficult for a server to guarantee whether a field is a file attachment or a text field, so our library simply puts all multipart fields into req.files.

**Comment by bigbao9494** [comment] 2023-06-02 03:05
@PixlRainbow thanks a lot

There must be a need:
1. Obtain the file uploaded through FormData in the interface [&] (const Request&/* req */, Response&res), and add some additional parameters, it's file_and_param.
2. Golang has a similar processing interface that handles this issue well. All parameters are in req.params (just read directly), and all files are in req.files.
3. I don't know if this can be achieved?

**Comment by PixlRainbow** [comment] 2023-06-02 06:16
After investigating golang source code and archived developer discussions, it appears that golang developers have taken the stance that if a field doesn't have a filename, then they will treat it as not a file.
Golang expects users who want to handle nameless file submissions to add their own middleware to inject a random file name if they expect a specific form field to always contain files.
Other libraries, such as python urllib3/urllib3#120 use a more complicated heuristic, as well as a means to dynamically recognize whether the older or the newer standards should be used (urllib3/urllib3#303)

**Comment by yhirose** [comment] 2023-06-02 07:04
@bigbao9494 @PixlRainbow thanks a lot for explaining and investigating this issue.

@PixlRainbow if this is not a bug and cpp-httplib doesn't provide a convenient way to handle this issue, I would like to close it and make a new issue to request what golang or urlib3 does. What do you think?

**Comment by PixlRainbow** [comment] 2023-06-02 07:19
The original topic of this issue was that the request content could not be found, and it has been determined that the request content is present if accessed in the documented way, thus the original issue has been resolved.

I agree that the new issue is that the designed/intended way of accessing form fields is not user friendly.

**Comment by bigbao9494** [comment] 2023-06-02 23:55
@PixlRainbow @yhirose 
Thank you for your professional and patient answers. This question can be concluded. Do I need to propose a new issue?

**Comment by yhirose** [comment] 2023-06-03 00:06
@bigbao9494 yes, you can send a new issue for a better way of accessing form fields.

**Closed** 2023-06-03 00:07 UTC
Labels: need more information to verify
