### ISSUE TITLE
Only one query param is recognized when query includes multiple ones

### ISSUE THREAD

**Issue by immccc** [yhirose/cpp-httplib#996] opened 2021-07-15 08:34 UTC
I am combining in the same URL both path and query params. Something like:

`https://localhost:8080/resources/resource-id?param1=foo&param2=bar`

Said that, server is defining a GET like:

```
srv.Get(R"/resources/([a-f0-9\\-]+))", [&](const Request& req, Response& res) {
    // ...		
}		
```

In this scenario, resource id is successfully mapped into a string variable.
But regarding query params

- param1 is retrieved ok:
  - `req.has_param()` returns **true**
  - value is "**foo**", the expected one. 
- param2 is NOT retrieved ok:
  - `req.has_param()` returns **false**

I am using version **0.7.13**

**Comment by immccc** [comment] 2021-07-15 11:31
Tried with version **0.8.5** as well, which has the title "_Fix problem with Get with Parameters_". But the error persists .

**Comment by yhirose** [comment] 2021-07-15 12:26
@immccc, thanks for the feedback, but I can't reproduce the problem. I added the following test to do so. (By the way, `R"/resources/([a-f0-9\\-]+))"` in your example can't be compiled. So I made small changes in the test case.)

https://github.com/yhirose/cpp-httplib/blob/215b81342e764ffd93402dc22eef43677fa62441/test/test.cc#L3720-L3724

**Comment by immccc** [comment] 2021-07-15 12:57
@yhirose thanks for taking your time on looking into this. 

could you please state on which version did you run the test on your comment?  

By the way, apologies for the regex, I made it a bit more generic than I have in my actual code and I forgot to check some syntax errors.

**Comment by yhirose** [comment] 2021-07-15 13:02
> could you please state on which version did you run the test on your comment?

The latest httplib.h in the master branch. This code has several fixes which will be released as **0.9.1** soon.
Hope it helps.

**Comment by immccc** [comment] 2021-07-15 13:06
Ok, sounds cool!

I will try with the latest stable one and, if not working, I have a workaround in mind that suits my specific case until 0.9.1 is released.

Thanks again for your help!

**Comment by yhirose** [comment] 2021-07-16 00:16
v0.9.1 is out. Please let me know if you still have this problem.

**Closed by yhirose** 2021-07-16 00:16 UTC
Labels: need more information to verify
