### ISSUE TITLE
Wrong Characters with Special Characters

### ISSUE THREAD

**Issue by lukasrmattos** [yhirose/cpp-httplib#715] opened 2020-10-22 03:18 UTC
Hi, first of all thanks for this amazing project.

So, I have problem in get request with special characters:

Sample: "Você" returns "Voc<inser random chars here">

My server is a ASP NET application and my client its C++ using this library.

In Postman I get everything ok.

How can I get the right encode?

**Comment by PixlRainbow** [comment] 2020-10-22 04:03
You are likely receiving the correct data, but not displaying it correctly. This library is not responsible for data processing, it simply gives you the received data as-is.
Unfortunately, from a quick Google search, there doesn't seem to be much agreement on how to display utf-8 extended characters in C++. There are lots of different methods people have come up with but no standardized way.

**Comment by yhirose** [comment] 2020-10-22 12:16
@lukasrmattos, thanks for the feedback. I guess the problem is that your terminal or command prompt can't show UTF8 response body from the server. One thing you could test it to dump the response body to a file, and open it on a text editor like VisualStudioCode which supports multiple encodings. As @PixlRainbow, mentioned, httplib.h is no responsible for data processing. So I'll close this issue. Please let me know if you think your problem relates to httplib.h. Thanks!

**Closed by yhirose** 2020-10-22 12:16 UTC
