### ISSUE TITLE
cpp-httplip 0.10.1 sends the request with encoded url https%3A 

### ISSUE THREAD

**Issue by HugoKuo** [yhirose/cpp-httplib#1385] opened 2022-09-05 15:08 UTC
cpp-httplip client-side log
`RuntimeError: HTTP GET error on 'https://demo.test.com/test-bucket/?encoding-type=url&list-type=2&prefix=userdata%2F' (HTTP 500)`

The object storage server-side log
`GET https%3A//demo.test.com/test-bucket/?encoding-type=url&list-type=2&prefix=userdata%2F HTTP/1.0 500 - cpp-httplib/0.10.1 `

**Comment by yhirose** [comment] 2022-09-05 18:43
@HugoKuo, thanks for the report, I don't understand the situation... Could you explain it more clearly, and also provide the smallest possible code snippet which reproduce the problem? Thanks!

**Comment by yhirose** [comment] 2022-09-06 01:44
Also could you show me which method is called in `Client` or `SSLClient`?

**Comment by charz** [comment] 2022-09-06 09:22
@yhirose Just curious, does the library send the `CONNECT <https>://<HOST>` before other request method?

```
CONNECT https://demo.test.com
GET https%3A//demo.test.com/test-bucket/ HTTP/1.1\r\n
```

**Comment by yhirose** [comment] 2022-09-06 11:07
@HugoKuo, could you show me the actual C++ code calling the `SSLClient::Get` method?

**Comment by yhirose** [comment] 2022-09-09 12:39
I'll close it since I don't receive any evidence that cpp-httplib really causes the problem. Thanks for your understanding!

**Closed by yhirose** 2022-09-09 12:39 UTC
Labels: need more information to verify
