### ISSUE TITLE
Download a file with Redirection corrupts the file data

### ISSUE THREAD

**Issue by gtnardy** [yhirose/cpp-httplib#889] opened 2021-03-31 21:14 UTC
If I download a file from a link (e.g: https://github.com/gtnardy/nanos-world-halloween/releases/download/v1.0.0/halloween.zip) which redirects me with `set_follow_location` enabled, it may end up adding the 'between' received data into my file:

Causing the top part of the file being the content before the file start to be downloaded itself:

![image](https://user-images.githubusercontent.com/6226807/113212407-1658fd80-924d-11eb-9764-1f98590f7c32.png)

I could identify with progress callback that the maximum size changed as well during the download:

Downloading 487/621.
Downloading 621/621.
Downloading 1378/1688665.
Downloading 1616/1688665.
Downloading 2994/1688665.
Downloading 4372/1688665.
...

Would that be a bug? Or should I try to handle that on my side?

**Comment by yhirose** [comment] 2021-04-01 18:17
@gtnardy, could you try the same with curl with auto redirect option? If curl handles it as you expect, the current behavior in cpp-httplib is a bug. Please let me know your result. Thanks!

**Comment by gtnardy** [comment] 2021-04-01 22:48
I've tested with curl on **linux** and **Invoke-WebRequest** on windows/powershell, both with redirection enabled (-L and -MaximumRedirection 10) downloads the file correctly and not corrupted.

I could do a workaround for this problem using `ResponseHandler` and getting the status 200 from it, after I get it, I move my file pointer to the beginning and it starts downloading the file itself.

**Comment by yhirose** [comment] 2021-04-02 02:44
@gtnardy, thanks for the excellent investigation. I think it's a bug. Could you do the workaround until I fix the problem? Hope I find time to work on this sometime this month.

**Comment by gtnardy** [comment] 2021-04-02 09:32
sure thing! thank you for this amazing lib!

**Comment by yhirose** [comment] 2021-04-05 15:41
@gtnardy, could you try the latest httplib.h? If it works on your machine, I'll release it.

**Comment by gtnardy** [comment] 2021-04-05 19:52
Tested! It does not writes to the file anymore =D! Thank you!

Some things I noticed:

It still "downloads" the first redirectional page, but does not trigger ContentReceiver which is great! But it still triggers ResponseHandler 200 when it redirects and also triggers Progress during downloading the redirectional page. I don't know if you think it is fine or not, but my progress bar goes from 0 to 100 (while redirecting), then starts going from 0 to 100 again to download the file ;)

The ResponseHandler only triggers once when it redirects, and do not triggers when it finishes, was it supposed to happen? (it does not bother me currently).

![image](https://user-images.githubusercontent.com/6226807/113619281-2d259880-962f-11eb-925e-f5808fe375b2.png)

![image](https://user-images.githubusercontent.com/6226807/113619384-475f7680-962f-11eb-9d32-d1ab4a021a36.png)

**Comment by yhirose** [comment] 2021-04-05 20:14
@gtnardy, good find! I updated my change. Could you try again?

**Comment by gtnardy** [comment] 2021-04-05 20:27
No more `ProgressHandler` before redirection 😊! (still `ResponseHandler` 200 just after redirection and no `ResponseHandler` at the end of download - are those a problem?)

![image](https://user-images.githubusercontent.com/6226807/113622853-e5edd680-9633-11eb-8aeb-e6de42b336d2.png)
![image](https://user-images.githubusercontent.com/6226807/113622972-1170c100-9634-11eb-9b20-7fdb76b08082.png)

**Comment by yhirose** [comment] 2021-04-05 21:46
@gtnardy, thanks for testing. That's what I expected. On the auto redirection mode, all the redirections before the final request will be completely ignored. I think the issue is now fixed. Thanks for your help!

**Closed by yhirose** 2021-04-05 21:46 UTC
Labels: bug

**Comment by gtnardy** [comment] 2021-04-05 22:42
Sounds good to me! Thank you!

**Comment by wangwenqiangGitHub** [comment] 2021-11-22 13:42
How use this lib Download big files
