### ISSUE TITLE
Crash in some unit tests on ASSERT failure

### ISSUE THREAD

**Issue by miketsts** [yhirose/cpp-httplib#730] opened 2020-11-01 17:17 UTC
@yhirose there seems to be additional bug with few unit tests:
```
KeepAliveTest.ReadTimeoutSSL
SSLClientServerTest.ClientCertPresent
SSLClientServerTest.MemoryClientCertPresent
SSLClientServerTest.TrustDirOptional
```
and maybe some more tests.
If the test fails for some reason (in my case it was the `SSL_ERROR_SYSCALL: Success` problem), then the entire unit test suite crashes, like below:
```
test.cc:3060: Failure
Value of: resb
  Actual: true
Expected: false
terminate called without an active exception
Aborted (core dumped)
```
It happens in v0.7.11.
I have simulated this problem by changing some `ASSERT_TRUE` to `ASSERT_FALSE`.
The crash happens because `join()` was called for the listen thread in a wrong state. I didn't investigate the problem further.

**Comment by yhirose** [comment] 2020-11-01 17:23
@miketsts, thanks for the info, but GitHub Actions CI passed all the tests and I haven't experience the error on my machine.
https://github.com/yhirose/cpp-httplib/actions/runs/332058410

Could you give more information to reproduce it?

**Comment by miketsts** [comment] 2020-11-01 18:14
@yhirose , yes if all tests are successful than all passes indeed. The problem happens if these specific tests fail for some reason - then the entire test suite crashes.
I have simulated this problem by changing some ASSERT_TRUE to ASSERT_FALSE inside the test to cause the test to fail.

**Comment by yhirose** [comment] 2020-11-01 19:00
@miketsts, I now understand what you meant. This is a problem caused by Google Test, and it seems they just ignored this problem here: https://github.com/google/googletest/issues/863

I know this situation is not convenient for you, but I can't do anything for it unless switching a different test framework like Catch2. Also it's not critical anyway. So I'll close this issue.

**Closed by yhirose** 2020-11-01 19:00 UTC
